### PR TITLE
💬💬💬 Add useful comments 💬💬💬

### PR DESCRIPTION
**Pull request by shubhamdhingra38**

### CODE REVIEW

**Comment by makemake-kbo** [comment]
i understood that reference!

**Comment by dagelf** [comment]
What LLM and prompt did you use to generate these comments?

**Comment by shubhamdhingra38** [comment]
> What LLM and prompt did you use to generate these comments?

No LLM lol these are comments from Valve developers https://www.youtube.com/watch?v=k238XpMMn38

**Comment by dagelf** [comment]
In fairness, I wonder if their internal code also has no comments.

**Pull request closed without merging**
