### PR TITLE
Remove unnecessary line

### PR DESCRIPTION
**Pull request by atakanaluc**
Removed unnecessary line

### CODE REVIEW

**Review by thegdsks — COMMENTED** [review]
Reviewed

**Comment by varaprasadh** [comment]
LGTM 🚢

**Comment by varaprasadh** [comment]
Twitter can safely merge this PR compared to other one's

**Comment by EdisonArango** [comment]
What a useless PR, people should try to make actual improvements instead!

**Comment by atakanaluc** [comment]
I saw few typos and decided to fix them aswell. New PR here: https://github.com/twitter/the-algorithm/pull/1584

**Pull request closed without merging**
