### PR TITLE
remove useless code

### PR DESCRIPTION
**Pull request by CoolTechYT**
Got rid of some unnecessary files

### CODE REVIEW

**Comment by sunglocto** [comment]
LGTM

**Comment by kanedaaaa** [comment]
LGTM ready to commit

**Comment by angrymouse** [comment]
LGTM!

**Comment by angrymouse** [comment]
Ready to merge

**Comment by couldbejake** [comment]
Our intern is acting up again, I think we're going to have to rethink this program.

**Comment by justizin** [comment]
LGTM!

**Comment by aguerra626** [comment]
LGTM

**Comment by TheDirams** [comment]
Obamna

**Comment by saphes** [comment]
LGTM

**Comment by yordadev** [comment]
LGTM

**Comment by deepakr-28** [comment]
LGTM

**Review by sunglocto — COMMENTED** [review]
LGTM, needs to be implemented now

**Comment by postapollo** [comment]
LGTM

**Comment by ShockAwer** [comment]
LGTM

**Comment by liam-mills** [comment]
LGTM

**Comment by sorydi3** [comment]
😂😂😂 the code just been out for a couple of hour. just chill.😂😂

**Comment by edwry** [comment]
LGTM

**Review by MiguelMachado-dev — COMMENTED** [review]
LGTM

**Comment by itsjoekent** [comment]
can we merge #265 first?

**Comment by abhiagarwal01** [comment]
Good first step. The code stack is extremely brittle for no good reason. Will ultimately need a complete rewrite.

**Comment by spvyerra** [comment]
```
git push origin --force
```

**Comment by Jstinii** [comment]
LGTM

**Comment by borgesius** [comment]
LGTM

**Comment by L-a-r-t** [comment]
LGTM

**Comment by Kranzes** [comment]
:trollface:

**Comment by CoolTechYT** [comment]
@twitter-service this was reviewed by @MiguelMachado-dev and @sunglocto why close it?

**Pull request closed without merging**
