### PR TITLE
fix: Vastly improve quality of tweet predicates (#121)

### PR DESCRIPTION
**Pull request by pizzaboxer**

### CODE REVIEW

**Comment by HyflerSD** [comment]
HMMM very good find there. Every user should be equally woke

**Comment by bluepilledgreat** [comment]
Let the de-elonmuskization begin!

**Review by biscuitehh — COMMENTED** [review]
LGTM

**Comment by joseeight** [comment]
This is sadness.
🚢

**Comment by regginator** [comment]
Fixes https://github.com/twitter/the-algorithm/issues/121?

**Review by karms — COMMENTED** [review]
Seems good, go ahead with merge.

**Comment by rekdacted** [comment]
Breaking-Bad-overdose

**Comment by callumisdumb** [comment]
+1 LGTM

**Comment by thebeanogamer** [comment]
LGTM

**Comment by 0x4da** [comment]
LGTM

**Comment by garbageman-phil** [comment]
:shipit:

**Comment by radifalco** [comment]
:shipit:

**Comment by PeasfulTown** [comment]
LGTM

**Comment by pizzaboxer** [comment]
you guys did not just reopen issue/pr contributions lmao what

FsLJyWMakAA2ziZ

**Comment by regginator** [comment]
> you guys did not just reopen issue/pr contributions lmao what
> 
> FsLJyWMakAA2ziZ
> 

https://user-images.githubusercontent.com/56618074/229227357-7938781a-9f3e-4f7d-b93c-4de3e15015e1.mp4

**Comment by leondz** [comment]
LGTM

**Comment by GodlyGH** [comment]
yeah please elon i dont want to see your shitty memes on my feed ty

**Comment by GodlyGH** [comment]
1984

**Comment by DiegoFleitas** [comment]
LGTM

**Comment by SerajMuftah** [comment]
Based

**Comment by WaviestBalloon** [comment]
Censorship by Elon yet again........ Please fix this

**Comment by mm12** [comment]
Please merge

**Pull request closed without merging**
