### PR TITLE
( ͡° ͜ʖ ͡°)

### PR DESCRIPTION
**Pull request by darkbanjo**
( ͡° ͜ʖ ͡°)

### CODE REVIEW

**Review by 0xEmma — COMMENTED** [review]
Very insightful additions

**Comment by michal-jenco** [comment]
this is exactly what Twitter has been missing ( ͡° ͜ʖ ͡°)

**Comment by darkbanjo** [comment]
i left my wallet in here have any of you seen ti

**Comment by NeroBlackstone** [comment]
fuck you.

**Review by Radu-D — COMMENTED** [review]
A man of culture I see!

**Review by sonigeez — COMMENTED** [review]
LFTM

**Comment by yani** [comment]
ಠ_ಠ

**Pull request closed without merging**
