### PR TITLE
Random bullshit go!!!!

### PR DESCRIPTION
**Pull request by SteampsonJake**
Hee hoo this was fun ngl x3

### CODE REVIEW

**Comment by drewman301** [comment]
LGTM

**Comment by RedGoldBelt** [comment]
Ready to merge?

**Comment by SteampsonJake** [comment]
Yup
100%

**Comment by DrewBarlow** [comment]
LGTM

**Comment by Foxlass** [comment]
LGTM

**Comment by matthew-kuhn** [comment]
LGTM

**Comment by nakoyasha** [comment]
this bullshit looks good to me

**Comment by quadsYT** [comment]
this is so good😩😩😩😩😩😩

**Comment by mateusmlo** [comment]
LGTM

**Pull request closed without merging**
