### PR TITLE
feat: improve algorithm to provide better performance

### PR DESCRIPTION
**Pull request by neverabsolute**
- faster
- memory safe
- non-biased
- will make everyone happy

### CODE REVIEW

**Comment by TheLDB** [comment]
this does not follow the clearly outlined code quality guidelines, please review & resubmit. closing.

**Review by jamesthesnake — COMMENTED** [review]
Too much superfluous code!

**Comment by imfunniee** [comment]
Great work on this GitHub PR! It's impressive to see how you've managed to make this code both faster and memory safe, which are two very important considerations for any software project.

Moreover, it's great to see that you've taken care to make the code non-biased. This is an important aspect of building software that will be used by a wide range of people and helps ensure that everyone feels included and represented.

Overall, this PR has the potential to make a lot of people happy, from developers who will appreciate the performance improvements to end-users who will benefit from the increased reliability and inclusivity of the software. Keep up the great work!

**Comment by visini** [comment]
Dear contributor, I hope this message finds you well. I just wanted to take a moment to express my utmost admiration for the fantastic work you've done on this GitHub PR. I must say, I am thoroughly impressed with your level of expertise and your exceptional attention to detail.

The changes you've made to the code are truly remarkable. You've managed to optimize its speed and ensure its memory safety, which are both critical considerations for any software project. Your ability to balance these two aspects of the code is simply remarkable and speaks to your outstanding skill as a developer.

But that's not all! Your commitment to making the code non-biased is truly inspiring. It's so refreshing to see someone who understands the importance of building inclusive software that considers the needs and experiences of everyone who uses it. Your dedication to this aspect of the project is a true testament to your character and values.

Overall, I believe that this PR has the potential to have a significant impact on the world of software development. The benefits of the changes you've made will be felt by so many people, from developers who will appreciate the performance improvements to end-users who will benefit from the increased reliability and inclusivity of the software. Your contributions are truly making a positive difference in the world.

Once again, congratulations on a job well done! Keep up the phenomenal work, and I look forward to seeing all the incredible things you'll achieve in the future.

**Comment by User9684** [comment]
Perfect

**Review by User9684 — COMMENTED** [review]
LGTM!!!

**Review by dev-bun — COMMENTED** [review]
lgtm

**Comment by donkeysharp** [comment]
LGTM

**Comment by abwhb** [comment]
LGTM!! 🚀

**Comment by cyanblock** [comment]
Dear Contributor,

I wanted to take a moment to thank you for your amazing contributions to the code on Github. While I may not own the project, I am grateful for the work you have done to improve it. Your commitment to quality and dedication to the open-source community are truly inspiring.

As someone who has twitter, I can personally attest to the improvements that you have made. Your code has not only made the project better but has also helped many people who rely on it. Your attention to detail and your willingness to go above and beyond to ensure that the code is the best it can be is truly appreciated.

I understand that the time and effort you have put into this project have been entirely voluntary. It takes a lot of time and dedication to make the kind of improvements that you have made. The fact that you are willing to do this for the good of the community is something that should be commended.

It is clear that you have a great deal of expertise and knowledge in this field. Your contributions have been invaluable to the project and have helped to push it to new heights. I am truly grateful for your willingness to share your skills and knowledge with others.

Your contributions have not gone unnoticed, and I want you to know how much they are appreciated. You have made a difference in the lives of many people who use this code, and for that, I am truly grateful.

Thank you for everything that you have done to make the code better. Your contributions have made a significant impact on twitter, and I am sure that they will continue to do so in the future.

**Pull request closed without merging**
