### PR TITLE
Improve algorithm

### PR DESCRIPTION
**Pull request by ridoy**
### Description

This PR implements a new recommendation algorithm for the Twitter timeline. The approach implemented here outperforms the current algorithm by several orders of magnitude in both speed and memory.

### CODE REVIEW

**Comment by shaped1** [comment]
LGTM!

**Comment by esond** [comment]
Nit: formatting

Test coverage is 💯, nice work!

**Comment by r351574nc3** [comment]
fixedit

**Comment by Nightcaat** [comment]
LGTM

**Comment by weston-bailey** [comment]
> The approach implemented here outperforms the current algorithm by several orders of magnitude in both speed and memory.

It's worth noting that this approach gives a much better user experience as well.

**Comment by Flova** [comment]
Definitely removes bloat and overhead

**Comment by lst4rk** [comment]
Crazy that you found this bug, I'm glad you caught it. LGTM!

**Comment by y0nei** [comment]
LGTM

**Comment by DanyPell** [comment]
Yet another nerd trying to be funny

**Comment by Neptuneia** [comment]
nice debloating

**Pull request closed without merging**
