### PR TITLE
Initialize Rust project 🦀

### PR DESCRIPTION
**Pull request by orhun**
Planting the first seeds.

We gotta start from somewhere.

### CODE REVIEW

**Comment by g3vxy** [comment]
Algo wasn't kawaii enough but now we are progressing.

**Comment by orhun** [comment]
Can I get a review pls?

**Comment by crescentrose** [comment]
LGTM :+1:

**Review by Kuriel23 — COMMENTED** [review]
This code has perfect!

**Review by baumflo — COMMENTED** [review]
LGTM 🚀

**Comment by 0xJepsen** [comment]
LGTM

**Comment by fazulk** [comment]
Its already there

**Comment by fazulk** [comment]
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/navi/navi/Cargo.toml

**Comment by vacekj** [comment]
finally, my twitter recommendations can be blazing fast.

**Pull request closed without merging**
