### PR TITLE
prefer scala.util.Try over try/catch

### PR DESCRIPTION
**Pull request by Ghurtchu**
`scala.util.Try` is nicer than default `try/catch`

### CODE REVIEW

**Comment by github-nilsson** [comment]
Stop changing the coding standard to the more error prone no-braces syntax.

**Comment by Ghurtchu** [comment]
> Stop changing the coding standard to the more error prone no-braces syntax.

Must be tough having no taste 😏.

**Comment by github-nilsson** [comment]
Well, that's the drawback of being a professional. Barr Group‘s Embedded C Coding Standard, Rule 1.3.a
> Braces shall always surround the blocks of code (a.k.a., compound statements), following if, else, switch, while, do, and for statements; single statements and empty statements following these keywords shall also always be surrounded by braces.

**Comment by github-nilsson** [comment]
Equally as relevant, if you want to change the coding standard do that in a separate PR that involves more than a few lines in one file.

**Comment by HeyBanditoz** [comment]
> Well, that's the drawback of being a professional. Barr Group‘s Embedded C Coding Standard, Rule 1.3.a
> 
> > Braces shall always surround the blocks of code (a.k.a., compound statements), following if, else, switch, while, do, and for statements; single statements and empty statements following these keywords shall also always be surrounded by braces.

**Comment by Ghurtchu** [comment]
> Well, that's the drawback of being a professional. Barr Group‘s Embedded C Coding Standard, Rule 1.3.a
> 
> > Braces shall always surround the blocks of code (a.k.a., compound statements), following if, else, switch, while, do, and for statements; single statements and empty statements following these keywords shall also always be surrounded by braces.

What does imperative C have to do with Scala that is expression oriented FP language?

Scope braces are good when you have more than one statement. 

I struggle to see a reason why would someone convolute the code with unnecessary braces 😄

**Comment by github-nilsson** [comment]
Excellent arguments to take up in a different issue where you suggest twitter to change its coding style.

**Comment by ilovelinux** [comment]
> > Stop changing the coding standard to the more error prone no-braces syntax.
> 
> Must be tough having no taste 😏.

Then it's not a technical PR. Please explain the advantages, if any. "It's nicer"/"Looks better to me" will never be good reasons for a PR.

**Pull request closed without merging**
