### PR TITLE
Spicy Chicken Sandwich

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
Thoughts on this chicken sandwich I made?

image

Please approve

### CODE REVIEW

**Comment by dayyan** [comment]
Was a thing in SF, no longer.

**Comment by Shivrager** [comment]
LGTM

**Comment by anurag-roy** [comment]
Looks tasty to me! Approved.

**Comment by streibeb** [comment]
LGTM!

**Review by fdebijl — COMMENTED** [review]
Please list the condiments before merging as per our style rules 🙏

**Comment by IsraPerez98** [comment]
Looks very good and tasty to me, now I'm hungry

**Comment by colton-boi** [comment]
lgtm, push to prod please

**Review by mustaphaelghoul — COMMENTED** [review]
:shipit: amazing work

**Comment by mutexdeveloper** [comment]
LGTM. Thanks for the contribution!

**Pull request closed without merging**
