### PR TITLE
fixed it

### PR DESCRIPTION
**Pull request by sadsciencee**
fixes all issues with the algorithm & improves performance

### CODE REVIEW

**Comment by angelonazzaro** [comment]
immagine

**Comment by kyeboard** [comment]
LGTM

**Comment by jobcmax** [comment]
lgtm

**Comment by NTDLS** [comment]
LGTM. Please merge ASAP.

**Comment by Jint3x** [comment]
LGTM!

**Comment by astranero** [comment]
Lgtm 🫢

**Comment by HrvojeJuric** [comment]
LGTM

**Comment by SteampsonJake** [comment]
I like it, it's quite minimalistic

**Comment by Waldimp** [comment]
LGTM

**Comment by iamtracy** [comment]
No conflicts, no regressions. Way she goes boys merge it

**Comment by 7PH** [comment]
Lesgo 😬

**Comment by TotalledZebra** [comment]
Outstanding work. Have you done any benchmarks with these new changes?

**Comment by davidhollenbeckx** [comment]
> Outstanding work. Have you done any benchmarks with these new changes?

Yep O(1) across the board, and memory usage way down. Due to the minimal size of the binary and significantly reduced calls to DB and elimination of all dependencies it can run on the edge with < 2 ms latency

Haven't had a chance to run in staging but it works on my machine

**Comment by akarahdev** [comment]
LGTM

**Comment by NTDLS** [comment]
> > Outstanding work. Have you done any benchmarks with these new changes?
> 
> Yep O(1) across the board, and memory usage way down. Due to the minimal size of the binary and significantly reduced calls to DB and elimination of all dependencies it can run on the edge with < 2 ms latency
> 
> Haven't had a chance to run in staging but it works on my machine

Should I submit a change request or are you ready to push this to prod now?

**Comment by hansonhqma** [comment]
lgtm

**Comment by AlfredGuimaz** [comment]
Where are the tests

**Comment by davidhollenbeckx** [comment]
> Where are the tests

GPT-4 is down so I didn't write any

**Comment by okaits** [comment]
lgtm

**Pull request closed without merging**
