### PR TITLE
simplify boolean expression

### PR DESCRIPTION
**Pull request by Ghurtchu**
rewrite
```scala
if (expression) true else false
```
to
```scala
expression
```

### CODE REVIEW

**Comment by hcresanti** [comment]
ship it

**Comment by Ghurtchu** [comment]
This will forever be my most kek PR.

**Comment by matinzd** [comment]
LTGM :))

**Comment by wannfq** [comment]
LGTM

**Comment by leonidius1123** [comment]
hope twitter learnt this lesson from you 👍

**Pull request closed without merging**
