### PR TITLE
Fix: Removed all ads from feed

### PR DESCRIPTION
**Pull request by alonzuman**

### CODE REVIEW

**Comment by jamesthesnake** [comment]
plus one

**Comment by 256k** [comment]
+1

**Comment by co-bby** [comment]
W

**Comment by austinhutchen** [comment]
+1

**Comment by HyflerSD** [comment]
LGTM!

**Comment by joshwcorbett** [comment]
I don't think this commit does anything lol

**Comment by austinhutchen** [comment]
> I don't think this commit does anything lol

LOL

**Comment by nonetrix** [comment]
lgtm

**Comment by 0xMukesh** [comment]
LGTM!

**Comment by logik93** [comment]
> Scam. For no scam go visit [Real Fake Photos](https://realfakephotos.com)

no.

**Comment by brookthomas** [comment]
Ship it

**Comment by byemc** [comment]
+1, I agree with this 100%

**Comment by alonzuman** [comment]
> I don't think this commit does anything lol

sorry, should have named it "WIP: ..."

**Comment by kuylar** [comment]
LGTM

**Comment by slweeb** [comment]
> I don't think this commit does anything lol

hater

**Comment by vovw** [comment]
LGTM

**Comment by logik93** [comment]
**LGTM**

**Comment by Xyphyn** [comment]
literally 1984

**Comment by angrymouse** [comment]
Reopen! Still actual!!!

**Comment by largemoron** [comment]
this should be reopened

**Comment by paxperscientiam** [comment]
OP, you'll have better luck with [gorhill/uBlock](https://github.com/gorhill/uBlock)

**Pull request closed without merging**
