### PR TITLE
Fix the algorithm

### PR DESCRIPTION
**Pull request by IsraPerez98**
I did it guys, I fixed Twitter

### CODE REVIEW

**Comment by sudhamjayanthi** [comment]
LGTM!

**Comment by sunglocto** [comment]
Literally 1984

**Comment by kristianka** [comment]
LGTM 👍 improves performance by 100% and removes bottlenecks

**Comment by thx1200** [comment]
Why was this closed?  This fixes Twitter more than any other tweak to the algorithm thus far.

**Comment by ghost** [comment]
1984
WHYYYYY

**Pull request closed without merging**
