### PR TITLE
Sick Engineering Role!

### PR DESCRIPTION
**Pull request by stevo2105**
[Whop](https://whop.com/) | Senior Full-Stack Engineer | In person (New York, NY) | Full-time | $170-220k base | [Link](https://jobs.polymer.co/whop/26288)

Whop is a marketplace where people sell access to communities and software they create. We process over $8M / month and have almost a million users. Whop is hiring across the board. We are venture backed and looking for incredibly talented folks to join us in our NYC office. We are located in Brooklyn.

We have a small engineering team where you will be able to make incredible impact. Please reach out to me on [Twitter](https://twitter.com/cultured) or apply through the link above.

We are only hiring for in person roles at this time so please don't reach out unless you are willing to move to NYC. We have a massive opportunity on our hands and need to be completely aligned!

:)

### CODE REVIEW

**Comment by Sanz009** [comment]
Advertising on GitHub as well 🤦

**Comment by JimColerick** [comment]
Kill yourself

**Comment by edoardottt** [comment]
Thank you for pointing out a company I'd never join

**Comment by GalvinPython** [comment]
no thank you

**Review by sarkiroka — COMMENTED** [review]
please remove the unnecessary blank line to merge

**Comment by shannonwells** [comment]
I need that job like I need a whop upside the head

**Comment by benjaminaheath** [comment]
I hope you get banned

**Pull request closed without merging**
