### PR TITLE
article "THE" added

### PR DESCRIPTION
**Pull request by K2adir**
The name "Social Graph Service" refers to a service that provides access to the social graph, which is a representation of the connections between users in a social network.

### CODE REVIEW

**Comment by K2adir** [comment]
The name "Social Graph Service" refers to a service that provides access to the social graph, which is a representation of the connections between users in a social network.

**Comment by cocomo29** [comment]
did u write tests for this? 🤔

**Comment by K2adir** [comment]
> did u write tests for this? 🤔

I asked my mom, she said its ok

**Comment by cocomo29** [comment]
can always count on moms! ✨

**Pull request closed without merging**
