### PR TITLE
April fools joke

### PR DESCRIPTION
**Pull request by quantumfate**
# April fools joke

Daddy Elon please tell me that you're just messing with the haters

### CODE REVIEW

**Comment by emanvidmaker** [comment]
This push deletes all files except ReadMe where it gets replaced by quantumfate 's mesage.
 Saved you a click

**Comment by Noah670** [comment]
This is real

**Review by stordahl — COMMENTED** [review]
gif

**Comment by 0xEmma** [comment]
Fixed a lot of issues

**Comment by Radu-D** [comment]
> Fixed a lot of issues

All of them, I would say!

**Comment by aerphanas** [comment]
nice

**Comment by favourdev1** [comment]
You need to be prosecuted😂😂

**Pull request closed without merging**
