### PR TITLE
Twitter is haram

### PR DESCRIPTION
**Pull request by agam778**
Please fix the issue. Twitter is haram.

### CODE REVIEW

**Comment by Mohammed-Abeer** [comment]
Ok

**Comment by JessyTsu1** [comment]
hhhhhhhh

**Comment by ExtReMLapin** [comment]
thank you for doing the needful sir

**Comment by jtbx** [comment]
This kind of crap might make the twitter guys reconsider open sourcing their spaghetti...

**Comment by sunglocto** [comment]
LGTM - الله أكبر

**Comment by jobcmax** [comment]
real

**Comment by Neptuneia** [comment]
nah its halal because its open source

**Comment by jtbx** [comment]
virbox server pr raid 🫡

**Comment by yhw2003** [comment]
luv this

**Comment by KavinK0001** [comment]
twitter haram

**Comment by jobcmax** [comment]
goofy ahh pr

**Comment by KavinK0001** [comment]
whar?

**Comment by farkhan777** [comment]
lmao, how?

**Comment by Vincent4440** [comment]
nice

**Comment by Neptuneia** [comment]
what the dog

**Pull request closed without merging**
