### PR TITLE
replace twitter with funny jpeg

### PR DESCRIPTION
**Pull request by riscmkv**
this is based

### CODE REVIEW

**Comment by Funtimes909** [comment]
This needs to be merged or I will eat my dog

**Comment by penguinencounter** [comment]
(if you're trying to see what it is, [here you go](https://github.com/twitter/the-algorithm/blob/892361f89ef5b96b590114a2eaf981f43b361d91/meme.jpg))

**Comment by toastyfen** [comment]
lgtm

**Comment by NotSuper** [comment]
i support this change

**Comment by joetessy** [comment]
lgtm

**Comment by 7MinutesDead-Git** [comment]
I have no conflicts with this branch

**Review by tom-ricci — COMMENTED** [review]
LGTM

**Review by aerphanas — COMMENTED** [review]
LGTM

**Comment by anedumgottil** [comment]
LGTM

**Comment by gruberdev** [comment]
A much needed feature, please merge ASAP.

**Review by Issodeveloper — COMMENTED** [review]
looks good to me

**Pull request closed without merging**
