### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by R4vitej4**

### CODE REVIEW

**Review by CorbanSurtees — COMMENTED** [review]
LGTM

**Comment by hoangphuc05** [comment]
this is a huge change, please break it down to smaller piece

**Comment by R4vitej4** [comment]
> this is a huge change, please break it down to smaller piece

This is my first open source contribution I know it is too too little 😂.

**Comment by mutexdeveloper** [comment]
A change like this might need some discussion,  I hope you understand due to the very controversial modifications. In the meantime will you please fix the conflicts, there's quite the list.

**Pull request closed without merging**
