### PR TITLE
Rust a Rewrite

### PR DESCRIPTION
**Pull request by CursedRock17**
Small Rewrite, would make twitter a bit cleaner and safer.

### CODE REVIEW

**Review by RoahNo — COMMENTED** [review]
LGTM

**Comment by VainXploits** [comment]
Day-Day-Daytrip took it to ten (Hey)
Ayy, Panini, don't you be a meanie
Thought you wanted me to go up
Why you tryna keep me teeny? I
It's a dream, he wished it on a genie
I got fans finally, ain't you wanting them to see me? I
I thought you want this for my life, for my life
Said you wanted to see me thrive, you lied
Just say to me what you want from me
Just say to me what you want from me
Ayy, Panini, don't you be a meanie
Thought you wanted me to go up
Why you tryna keep me teeny now?
Now they need me, number one on streamin'
Oh yeah, you used to love me
So what happened, what's the meaning? I
I thought you want this for my life, for my life
Said you wanted to see me thrive, you lied
Now when it's all done, I get the upper hand
I need a big Benz, not another fan
But I still want you as a fan
I'ma need to sit down, don't mean to make demands
But I need you to...
Say to me what you want from me
Just say to me what you want from me
D-D-Daytrip took it to ten (Hey)

**Comment by martinmortier** [comment]
LGTM

**Review by harshjohar — COMMENTED** [review]
LGT(elon musk alt account)M

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Pull request closed without merging**
