### PR TITLE
ඞඞඞඞඞඞඞඞ Add Among Us Amogi Sussy Baka ඞඞඞඞඞඞඞඞ

### PR DESCRIPTION
**Pull request by shubhamdhingra38**

### CODE REVIEW

**Comment by sunglocto** [comment]
LGTM

**Review by Radu-D — COMMENTED** [review]
We need this!

**Comment by ArchitW** [comment]
🔴 Flagged!

**Comment by shubhamdhingra38** [comment]
> ArchitW

🤓

**Review by raihanadf — COMMENTED** [review]
LGTM!

**Comment by y0nei** [comment]
How in the world?!

Also LGTM

**Comment by Arsik0153** [comment]
LGTM ready to merge

**Comment by GemedetAdept** [comment]
Can confirm. It's a bit hidden in the documentation, but benchmarks prove that adding Among Us Sussy Baka improves the efficiency of the codebase by at least 47%.

**Comment by makitard** [comment]
LGTM

**Review by TusharAthare — COMMENTED** [review]
LGTM!!

**Comment by gluonsandquarks** [comment]
can someone please uwu-ify this repo??

**Review by Romanok2805 — COMMENTED** [review]
LGTM

**Comment by prenaissance** [comment]
ඞඞඞඞඞඞඞඞ

**Comment by pedrogamedev** [comment]
lgtm

**Review by wgw0 — COMMENTED** [review]
Solid changes, approved.

**Review by matias-gonz — COMMENTED** [review]
lgtm 👍

**Comment by okaits** [comment]
Lgtm

**Pull request closed without merging**
