### PR TITLE
fix: Better recommendations on timeline. 

### PR DESCRIPTION
**Pull request by abstraq**

### CODE REVIEW

**Comment by pizzaboxer** [comment]
+1 i think this would contribute a lot to the twitter experience

**Comment by bluepilledgreat** [comment]
LGTM

**Comment by ShauryaB537** [comment]
This is actually good. +1

**Comment by nonetrix** [comment]
lgtm

**Comment by jowrjowr** [comment]
CI has passed. ship it.

**Comment by NiciusB** [comment]
LGTM!

**Comment by xiaohk** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: 
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:

**Comment by mahapsub** [comment]
🐝

**Comment by lucasnethaj** [comment]
wise words sir

**Comment by vexorian** [comment]
It makes the most sense.

**Comment by neverabsolute** [comment]
lgtm

**Comment by im-alfa** [comment]
legend

**Comment by GalvinPython** [comment]
I like this change

**Comment by mohammedsahl** [comment]
LGTM ship it!

**Review by aashari — COMMENTED** [review]
LGTM

**Comment by pinguinosod** [comment]
Top 💯💯💯🤌🤌

**Comment by SoulNinja-dev** [comment]
:shipit: 💀

**Comment by ts-3156** [comment]
The best PR ever

**Comment by monospacedigital** [comment]
Lgtm

**Review by davidkrammer — COMMENTED** [review]
Dont change it to 0. Instead better rank blue verfied way higher 🚀

**Comment by witcheslive** [comment]
These are the kind of improvements we're looking for in open sourcing the algorithm. Deploy immediately.

**Review by Rotinx — COMMENTED** [review]
Perfect

**Comment by edprats** [comment]
LGTM

**Comment by Bibekdhkl** [comment]
The Best PR Ever!

**Review by lRaulMN7 — COMMENTED** [review]
SHIP SHIP SHIP.

**Comment by videah** [comment]
LGTM 👍

**Review by rmcmk — COMMENTED** [review]
LGTM

**Comment by manuelbasanta** [comment]
Approved

**Comment by znwhite** [comment]
Excellent work

**Comment by zroyer** [comment]
LGTM :shipit:

**Review by TheDevMinerTV — COMMENTED** [review]
LGTM

**Review by zroyer — COMMENTED** [review]
LGTM :shipit:

**Review by willbrandin — COMMENTED** [review]
send it

**Comment by radoslawgrochowski** [comment]
lgtm

**Comment by xypwn** [comment]
Brilliant

**Comment by DavidBuchanan314** [comment]
Why not a negative weight?

**Comment by es3n1n** [comment]
lgtm

**Comment by visini** [comment]
✅

**Comment by 0xMukesh** [comment]
LGTM, ship it

**Review by cbackas — COMMENTED** [review]
LGTM

**Comment by RinLovesYou** [comment]
Lgtm, ship to prod 👍

**Comment by KKcorps** [comment]
LGTM

**Comment by juuuuurien** [comment]
LGTM 🚀

**Comment by bishpls** [comment]
🚢 🇮🇹 

:shipit:

**Comment by videah** [comment]
image

**Comment by malonehedges** [comment]
approved

**Comment by swiftwuz** [comment]
not all heroes wear capes

**Comment by PennyBunny** [comment]
Lgtm, it's ready

**Comment by rburhum** [comment]
Build and ship it. Go go go!

**Review by yellowsink — COMMENTED** [review]
LGTM; ship it

**Comment by lucasgelfond** [comment]
LGTM

**Comment by smiba** [comment]
Key contribution, should be instantly deployed on production

**Comment by ryandils** [comment]
lgtm

**Comment by rekdacted** [comment]
FnmpvHBakAApcZR

**Comment by RyanMarr** [comment]
🚢

**Comment by jcfrancisco** [comment]
:shipit:

**Review by twofactor — COMMENTED** [review]
Ship it

**Review by KevinDenys — COMMENTED** [review]
must have

**Comment by JohnyTheCarrot** [comment]
lgtm

**Comment by mohammedsahl** [comment]
Most definitely one of the PRs of all time

**Comment by gabrielduete** [comment]
😎

**Comment by gfernandez55** [comment]
LGTM

**Comment by blindmodz** [comment]
LGTM

**Comment by heyskylark** [comment]
Haven't seen such beautiful code in years, ship it 🚀

**Comment by lukeify** [comment]
Hi @maksimru, it's Elon here. Why did you close this? Please merge this immediately—we haven't done enough to reduce our valuation so far, we need to go lower. 

First principles, yada yada.

**Comment by MatheusMuriel** [comment]
Very Nice

**Review by 3zachm — COMMENTED** [review]
lgtm!
already benefiting so much from open source ^^

**Comment by nadenf** [comment]
I just want to say that I am proud of this community. This is going to make a huge difference to many lives. 

@maksimru .. LGTM !

**Comment by thx1200** [comment]
This would be the best fix to Twitter of all time.

**Comment by SED4906** [comment]
OwO

**Comment by sshipsey** [comment]
LGTM

**Comment by themcaffee** [comment]
LGTM :sunglasses:

**Comment by isacmoura** [comment]
I can't find the unit tests for your solution. Declining

**Comment by bethac07** [comment]
LGTM, must have been closed by accident

**Comment by yungifez** [comment]
This is game changing

**Review by shadeofsound — COMMENTED** [review]
LGTM

**Comment by jowrjowr** [comment]
@maksimru please bring this to elon's attention immediately this is a critical PR

**Comment by OKNewman** [comment]
> I can't find the unit tests for your solution. Declining

The change is just 4 hard-coded values. Shouldn't there already be unit tests in place from the original implementation?

**Comment by toasterrepairman** [comment]
LGTM (i dont use twitter)

**Review by coreyg142 — COMMENTED** [review]
LGTM!

**Comment by abudabid** [comment]
This post has been fact checked by real senior algorithm engineer : true ✅

**Comment by cjwillia** [comment]
🫡🚀

**Review by cjwillia — COMMENTED** [review]
🫡🚀

**Review by blainehoyt — COMMENTED** [review]
lgtm

**Comment by intincrab** [comment]
uwu

**Comment by parion** [comment]
Definitely fixes this user story. 

As a **TWITTTER USER** I would like **TO SEE NO VERIFIED TWEETS** so that I **CAN ACTUALLY USE TWITTER WITHOUT GETTING UPSET**. 

Ship it. 🚀

**Comment by mxcaud** [comment]
Wow the PR was closed? Could of gotten your $20 billion back

**Comment by bharatchills** [comment]
uwu

**Comment by Gr770** [comment]
Ship it

**Comment by kehrazy** [comment]
LGTM

**Comment by raftario** [comment]
i assume closing this was a mistake, should probably reopen. lgtm

**Comment by RetroDreams** [comment]
Be sure to go tell `@martianoff` on Twitter how you feel about him closing this PR

**Comment by RinLovesYou** [comment]
Imagine closing a legitimate PR like this without giving any reason. Twitter recommending me unfunny people who have paid their way into my timeline is ridiculous. My for you should consist of people i follow, their likes, and similar content. I do not care for promotion of funny "premium" users. They have their audience, they don't need the extra reach.

**Comment by northmaster** [comment]
LGTM!

**Comment by kururuchan** [comment]
LGTM from me.

**Comment by TheDukeDK** [comment]
> CI has passed. ship it.

:rofl: 
image

**Review by NeelAPatel — COMMENTED** [review]
Unsure why this is closed, the proposed changes would indeed give back the reverse chronological order of tweets we desire. 

Transparency  and honesty used to be the bread and butter of twitter before The Algorithm. 

Must merge immediately post haste, LGTM 🚀

**Comment by maxix54** [comment]
LGTM, reopen this.

**Comment by addisonlynch** [comment]
LGTM

**Comment by fishe-tm** [comment]
LGTM

**Comment by sidedwards** [comment]
LGTM :shipit:

**Comment by AlexFlipnote** [comment]
LGTM 👍👍

**Comment by tomatoavocadosandwich** [comment]
+1

**Comment by richardjohn** [comment]
Ship it! 🚀

**Comment by orbtz** [comment]
LGTM 🚀

**Comment by erickdewa** [comment]
It is better😂🤌

**Review by Zurga — COMMENTED** [review]
👍

**Review by santumerino — COMMENTED** [review]
I can only assume that this PR was closed by mistake. This looks like a clear improvement to me.

**Review by hexandcube — COMMENTED** [review]
👍 This is a great improvement to The Algorithm™ which will make Twitter a lot better

**Comment by cperdiansyah** [comment]
LGTM 🚀

**Review by onedr0p — COMMENTED** [review]
Approved

**Review by nouraellm — COMMENTED** [review]
LFGTM!

**Comment by chixPL** [comment]
LGTM

**Comment by thomiceli** [comment]
LGTM 👍

**Comment by thomiceli** [comment]
LGTM

**Comment by adrianarandac** [comment]
Quality PR in here

**Review by thomiceli — COMMENTED** [review]
LGTM

**Comment by synap5e** [comment]
How do I install this version of twitter? Is this repo missing a releases page?

**Comment by Haaroon** [comment]
LGTM how to approve?

**Comment by rburhum** [comment]
> LGTM how to approve?

I approve it. Who else wants to approve it? Ship it! lol

**Pull request closed without merging**
