### PR TITLE
Remove all files

### PR DESCRIPTION
**Pull request by Nightcaat**
This PR removes all files from the repository, as chronological order is objectively better.

### CODE REVIEW

**Review by Nightcaat — COMMENTED** [review]
LGTM

**Comment by Willy-Gilly** [comment]
bro... why

**Comment by zxcodes** [comment]
🤣

**Comment by BurnerWah** [comment]
LGTM

**Comment by nwithan8** [comment]
LGTM, merge.

**Comment by 28development** [comment]
LGTM 🚀 🌎  💣

**Comment by canercetin-randomguy** [comment]
LGTM, lets make this modern highly scalable Ethereum blockchain based IPFS powered PAAS robust async framework cross-platform write once deploy everywhere cost-saving microservice agile algorithm hypervisor extended HTML rich-client shared NoSQL kubernetes JSON storage decentralized functional bug-free docker CSS web apps that use the decentralized web - Web 3.0, the serverless internet, where the users are in control of their own data, identity, and destiny model algorithm.

**Comment by Kapil-Bhattarai** [comment]
LGTM :D

**Comment by PPatton95** [comment]
!

**Comment by xcscxr** [comment]
😶‍🌫️

**Comment by blake-c-aggienetwork** [comment]
LGTM, pls merge

**Comment by LEQUI000** [comment]
lgtm

**Comment by canercetin-randomguy** [comment]
where merge, every millisecond lost waiting for this performance optimization is damage to user experience.

**Comment by Nightcaat** [comment]
Not gonna lie I read absolutely none of that

**Comment by canercetin-randomguy** [comment]
please sign that lmao

**Comment by Nightcaat** [comment]
I really wanna sign it but cla-assistant is being really unresponsive and I am still under a rate limit 10 minutes later. Will keep you all updated
There is no CLA to sign for twitter/the-algorithm. (upstream connect error or disconnect/reset before headers. reset reason: connection termination)
There is no CLA to sign for twitter/the-algorithm. (API rate limit exceeded for user ID 18583677.)

**Comment by fancythedeveloper** [comment]
This fix is so easy, how did they not notice it?

**Comment by tamatamvan** [comment]
169395143-3597690d-9f4a-46e0-be3d-3acd8c3c7630

**Comment by berkezircan** [comment]
LGTM !!

**Comment by kanarian** [comment]
LGTM! nice job

**Comment by canercetin-randomguy** [comment]
hours passed by, still no merge...

**Review by danielgospodinow — COMMENTED** [review]
Nice one ✅

**Comment by WilliamApted** [comment]
lgtm

**Comment by Nukeuler123** [comment]
LGTM, the performance gains are insane

**Comment by Dakedres** [comment]
LGTM, pls merge this would restore my workflow

**Comment by wtflmao** [comment]
Merge ASAP

**Comment by MuhammedELSayedBrq** [comment]
هو ده الcommit التمام👌

**Comment by MuhammedELSayedBrq** [comment]
+201067318767

**Comment by CommanderTvis** [comment]
I approve

**Comment by canercetin-randomguy** [comment]
@maksimru BOOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request closed without merging**
