### PR TITLE
Fix: src deleted to increase algorithm performance

### PR DESCRIPTION
**Pull request by Gabrielm3**
src folder deleted to increase algorithm performance.

trust the strategy.

1 Abril :)

### CODE REVIEW

**Comment by syedaqib112** [comment]
This PR will never be merged 😂😂

**Review by ayomide-snr — COMMENTED** [review]
LGTM 👍 😂

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by Davidththird** [comment]
> 

shut the fuck up ad bot kill yourself

**Pull request closed without merging**
