### PR TITLE
Why should russia's illegal invasion of ukraine be singled out in SpaceSafety?

### PR DESCRIPTION
**Pull request by gilescope**
Shouldn't some more generic topic(s) be created if need be? Are the existing categories not sufficient to capture problematic content? This topic seems not to be generic enough - if this topic is singled out, then why not others? Where does the line get drawn. I think this needs to be rethought a little.

(Appreciate the bravery of open sourcing the algorithm for inspection. Kudos for this.)

### CODE REVIEW

**Comment by Laim** [comment]
I assume it would've been in relation to a lot of the fake content that was being tweeted out including deep fakes.  As it's an on-going conflict, it was likely made for easier searching of specifically flagged content in regards to the invasion. 

As it's only just gone OS, there's nothing to say that similar things haven't been done in the past and removed instead of being deprecated.

**Comment by glaiveeeeeee** [comment]
it's singled out because it's the only legitimate war in the past 100 years

and we are tired of dumb Eastern Europeans crying about it

**Comment by 0cv** [comment]
What about https://github.com/twitter/the-algorithm/blob/main/visibilitylib/src/main/scala/com/twitter/visibility/rules/PublicInterestRules.scala#L54-L79 ?

**Comment by gilescope** [comment]
`MisinfoPropaganda` might be the more generic category for `MisinfoCrisis`?

**Comment by laverix** [comment]
+

**Comment by laverix** [comment]
+1

**Comment by hamzahsn** [comment]
I think this is a very political opinion rather than opening a request cause it's Twitter's policy...let's not forget that most of these open PRs will in stale and others will be merged.

**Comment by hamzahsn** [comment]
I think this is a very political opinion rather than opening a request cause it's Twitter's policy...let's not forget that most of these open PRs will in stale and others will be merged.

**Comment by 0cv** [comment]
@hamzahsn is it written somewhere in the Twitter's policy that the Russian war shall be treated any differently from any other war? Is this code not reflecting the personal opinion of some Twitter's executives instead?

**Comment by hamzahsn** [comment]
@0cv I'm not against what you saying but this will open an endless loop of such topics also I'm not aware of what is written in Twitter's policy but I'm pretty sure they didn't restrict some things just like that.

**Review by Thexumaker — COMMENTED** [review]
Lgtm

**Comment by glaiveeeeeee** [comment]
> @hamzahsn is it written somewhere in the Twitter's policy that the Russian war shall be treated any differently from any other war? Is this code not reflecting the personal opinion of some Twitter's executives instead?

Not everything has to be written down; in this case, it's just common sense to treat the only legitimate war in the past century different.

**Comment by webknjaz** [comment]
> we are tired of dumb Eastern Europeans crying about it

**Comment by glaiveeeeeee** [comment]
> > we are tired of dumb Eastern Europeans crying about it
> 
> 
> 
> Sounds like you are trying to make excuse for normalizing genocide apologism. How are you feeling?
> 
> 
> 
> Jeez. That's very western of you 🤡. And ruscist, of course.
> 
> 
> 
> Let me leave this for you if you ever decide to self-educate.
> 
> [Stand With Ukraine](https://stand-with-ukraine.pp.ua)

The only one genociding Ukraine is Zelensky image

**Comment by webknjaz** [comment]
> The only one genociding Ukraine is Zelensky

Oh boi. So you're one of those terrorist supporters. Like elon, right?

**Comment by brnteka** [comment]
> > > we are tired of dumb Eastern Europeans crying about it
> > 
> > 
> > Sounds like you are trying to make excuse for normalizing genocide apologism. How are you feeling?
> > Jeez. That's very western of you 🤡. And ruscist, of course.
> > Let me leave this for you if you ever decide to self-educate.
> > [Stand With Ukraine](https://stand-with-ukraine.pp.ua)
> 
> The only one genociding Ukraine is Zelensky image

Seems you are just a troll that's here to derail the discussion and make a mess out of it.

I suggest to ignore him.

PS kys Zombie

**Comment by nlucansk** [comment]
Cmon merge it!

**Comment by danielhaim1** [comment]
Cross referencing issue #1489 with additional valid points.

**Comment by fbondeaux** [comment]
> > we are tired of dumb Eastern Europeans crying about it
> 
> Sounds like you are trying to make excuse for normalizing genocide apologism. How are you feeling?
> 
> Jeez. That's very western of you 🤡. And ruscist, of course.
> 
> Let me leave this for you if you ever decide to self-educate. [Stand With Ukraine](https://stand-with-ukraine.pp.ua)

Hardly anybody cares about your war except for the people that are 24/7 online. Just look at our outdated equipment that you lot receive. You've been played for a fool. All attempts to draw the west into this war has failed which I think is mainly to do with the vile propaganda that Ukraine is the "bastion of democracy" while Ukrainian soldiers has been featured multiple times on NY Times et al. for their war crimes. How can anyone in Gods name slash someones throat or stab someone eyes? Ukrainians are not normal people.

**Comment by Thexumaker** [comment]
this is github not twitter... No need to spew russian propaganda and racism on here : )

**Comment by srghma** [comment]
@glaiveeeeeee @fbondeaux GUYS GUYS GUYS, you say this because You dont know the history - namely "[Yanukovich was a dictator and agent of putin, ....](https://twitter.com/srghma/status/1773319318228341203) (even [David Deutsch reposted me](https://twitter.com/srghma/status/1774397705504329734))

also:
1. [MY friend was tortured](https://twitter.com/srghma/status/1766051685632188546) 
2. ["I killed a child with my own hands"](https://twitter.com/srghma/status/1698102935576821899)
3. [russians want to attack Estonia](https://news.err.ee/1608981665/ex-prime-minister-dmitry-medvedev-baltic-states-belong-to-russia) but this doesnt make sense because [humans will defeat death](https://twitter.com/srghma/status/1671376036590649346)


more https://srghma.github.io/ukraine-on-fire https://srghma.github.io/war https://srghma.github.io/china https://srghma.github.io/fuck-the-long-experiments

other interesting topics - https://srghma.github.io/how-life-was-created


--------------

@glaiveeeeeee 

> dumb Eastern Europeans

Its us, ukrainians. Right?

My reply - https://github.com/twitter/the-algorithm/issues/1497#issuecomment-2034217951

What country You are from?

China? ("China helps russia after Bucha" is equal to "Germany helps Japan after Unit 731". Also China is occupant of Tibet like russia is occupant of Moldova, Georgia, Ukraine. History is cyclical, You know?)

> genociding Ukraine is Zelensky

no, he is saving

https://twitter.com/srghma/status/1774584888605442122

--------------

@fbondeaux

> people that are 24/7 online

yes, I'm 24/7 online

My father is in army, my mother is crying "russians approach". 
My step brother and step sister are from Bahmut, two families are without homes.
 Soon will come my time to say goodbye to Rodynskoye.
russians tortured my friend https://twitter.com/srghma/status/1766051685632188546

> Just look at our outdated equipment that you lot receive. You've been played for a fool

https://twitter.com/srghma/status/1774135349142585578

> slash someones throat or stab someone eyes

You mean this maybe-fake created by putin https://fakty.ua/ru/399306-radi-fejkov-quot-voskreshayut-quot-lyudej-propagandisty-rf-obvinili-v-pytkah-rossijskogo-soldata-zhitelya-vinnicy-umershego-5-let-nazad ? ("putin blows up houses" to start war in Checknya, You heard?) 


> Ukrainians are not normal people.

but yes, I do believe ukrainian soldiers did other horrible things (why not if even [America was crazy](https://twitter.com/srghma/status/1774665183803453521) - "Americans wanted to help Vietnam to build roads, but couldnt control their dogs AAAAAND soldiers became crazy and started throw napalm on heads of ordinary people")

BUT:
1. WHO have opened "gates of hell"????? Putin and only putin [1](https://twitter.com/srghma/status/1773319318228341203) [2](https://twitter.com/srghma/status/1773891822496129273)
4. these atricities happened when? during Poroshenko. Poroshenko is who? [agent of putin](https://twitter.com/srghma/status/1772976858671337479) (buhus info, "Medvedchuk recordings", he was sending money to russian occupants in Donetsk)

**Comment by fbondeaux** [comment]
> @glaiveeeeeee @fbondeaux GUYS GUYS GUYS, you say this because You dont know the history - namely "[Yanukovich was a dictator and agent of putin, ....](https://twitter.com/srghma/status/1773319318228341203) (even [David Deutsch reposted me](https://twitter.com/srghma/status/1774397705504329734))
> 
> also:
> 
> 1. [MY friend was tortured](https://twitter.com/srghma/status/1766051685632188546)
> 2. ["I killed a child with my own hands"](https://twitter.com/srghma/status/1698102935576821899)
> 3. [russians want to attack Estonia](https://news.err.ee/1608981665/ex-prime-minister-dmitry-medvedev-baltic-states-belong-to-russia) but this doesnt make sense because [humans will defeat death](https://twitter.com/srghma/status/1671376036590649346)
> 
> more https://srghma.github.io/ukraine-on-fire https://srghma.github.io/war https://srghma.github.io/china https://srghma.github.io/fuck-the-long-experiments
> 
> other interesting topics - https://srghma.github.io/how-life-was-created
> 
> if you want to talk with me - we can make a video for Youtube
> 
> @glaiveeeeeee
> 
> > dumb Eastern Europeans
> 
> Its us, ukrainians. Right?
> 
> My reply - [#1497 (comment)](https://github.com/twitter/the-algorithm/issues/1497#issuecomment-2034217951)
> 
> What country You are from?
> 
> China? ("China helps russia after Bucha" is equal to "Germany helps Japan after Unit 731". Also China is occupant of Tibet like russia is occupant of Moldova, Georgia, Ukraine. History is cyclical, You know?)
> 
> > genociding Ukraine is Zelensky
> 
> no, he is saving
> 
> https://twitter.com/srghma/status/1774584888605442122
> 
> @fbondeaux
> 
> > people that are 24/7 online
> 
> yes, I'm 24/7 online
> 
> My father is in army, my mother is crying "russians approach". My step brother and step sister are from Bahmut, two families are without homes. Soon will come my time to say goodbye to Rodynskoye. russians tortured my friend https://twitter.com/srghma/status/1766051685632188546
> 
> > Just look at our outdated equipment that you lot receive. You've been played for a fool
> 
> https://twitter.com/srghma/status/1774135349142585578
> 
> > slash someones throat or stab someone eyes
> 
> You mean this maybe-fake created by putin https://fakty.ua/ru/399306-radi-fejkov-quot-voskreshayut-quot-lyudej-propagandisty-rf-obvinili-v-pytkah-rossijskogo-soldata-zhitelya-vinnicy-umershego-5-let-nazad ? ("putin blows up houses" to start war in Checknya, You heard?)
> 
> > Ukrainians are not normal people.
> 
> but yes, I do believe ukrainian soldiers did other horrible things (why not if even [America was crazy](https://twitter.com/srghma/status/1774665183803453521) - "Americans wanted to help Vietnam to build roads, but couldnt control their dogs AAAAAND soldiers became crazy and started throw napalm on heads of ordinary people")
> 
> BUT:
> 
> 1. WHO have opened "gates of hell"????? Putin and only putin [1](https://twitter.com/srghma/status/1773319318228341203) [2](https://twitter.com/srghma/status/1773891822496129273)
> 2. these atricities happened when? during Poroshenko. Poroshenko is who? [agent of putin](https://twitter.com/srghma/status/1772976858671337479) (buhus info, "Medvedchuk recordings", he was sending money to russian occupants in Donetsk)

I just don't care, you are all a bunch of corrupt assholes from Moscow all the way to Kiev. Atrocities from both sides have appeared yet Ukrainians themselves always cry wolf. Kneecapping soldiers, beheadings, testicle removal, burning soldiers alive: Russians and Ukrainians two sides of the same coin. Beasts, animals; there is no place for you here in Europe.

The defense ministers and his ilk have been stealing our donated money and is now fired. Zelensky himself sitting on mountains of cash. That's why nobody gives a F about your war; your leadership is stealing our money and equipment.

I'm from the Netherlands and in 2016 we had a referendum where we voted against the association agreement with Ukraine.

You see, we here knew in 2016 that you are just stealing bandits. So no, your propaganda only works online. Not in the real world. If there is a God, this war is just to make sure your corrupt bloodline is eradicated.

Now, get in the trench and die for Reznikov et al.

**Comment by webknjaz** [comment]
@fbondeaux go away, ruscist nazi 🤡 🤡 🤡

**Pull request closed without merging**
