### PR TITLE
:warning: Fixes *all*  twitter issues :warning: 

### PR DESCRIPTION
**Pull request by tornikeo**
No twitter - no issues

Update:

:memo: Just signed the CLA to make sure this PR goes public quickly. :zap: . Poor twitter ~~addicts~~ users need this BAD!

### CODE REVIEW

**Comment by albgus** [comment]
LGTM

**Review by devvsakib — COMMENTED** [review]
Approved by Twitter. Thanks for your help😂

**Comment by pixrr** [comment]
🧠

**Comment by MertBalkan** [comment]
what the...

**Comment by tornikeo** [comment]
:memo: Just signed the CLA to make sure this PR goes public quickly. :zap: . Poor twitter ~~addicts~~ users need this BAD!

**Review by KajeArch — COMMENTED** [review]
Obvious nonsense. As a word of advice, it would be wise not to waste your time during your office breaks submitting asinine and pointless pull requests on GitHub.

**Review by harshkhandeparkar — COMMENTED** [review]
LGTM

**Comment by matheusPereiraG** [comment]
LMAO

**Comment by dagelf** [comment]
Your fascist, globalist, freedom-hating, oppressive overlords approve. Those who love freedom, however, don't.

**Comment by tenosiswono** [comment]
LGTM

**Comment by madibaT** [comment]
haha, looks good to be merged 👍

**Comment by footvaalvica** [comment]
LGTM

**Comment by devByGelu** [comment]
LGTM

**Review by Doges — COMMENTED** [review]
LGTM!

**Comment by deviant-semicolon** [comment]
LGTM

**Comment by buenaflor** [comment]
Great contribution! LGTM 🚀

**Comment by istiakshihab-office** [comment]
LGTM  👍
Initiate Merge asap.

**Comment by h3llo-wor1d** [comment]
LGTM

**Pull request closed without merging**
