### PR TITLE
Important company-related fixes, please merge ASAP

### PR DESCRIPTION
**Pull request by marvac**
See title

### CODE REVIEW

**Comment by Furry** [comment]
I love it

**Comment by y0nei** [comment]
Based

**Comment by aerphanas** [comment]
why beloffgs ?

**Comment by CharlesStover** [comment]
>why beloffgs

"Beloffgs" is an unfortunate casualty of this War on Free Speech driven by the Fake News Media. We cannot risk these evil news corporations finding any references to "Elon" in the codebase, as that would imply bias and deteriorate trust.

less trust = less revenue = less free speech

If we don't want the communists to win, we have to accept that the English language, insofar as the Twittersphere is considered, now contains beloffgs.

**Comment by v1nsai** [comment]
LGTM

**Review by aldenreed — COMMENTED** [review]
Haha I love it, LGTM

**Pull request closed without merging**
