### PR TITLE
Replaces all filename underscores and hyphens with transgender flags for inclusivity 🏳️‍⚧️

### PR DESCRIPTION
**Pull request by anthdono**

### CODE REVIEW

**Review by lisanna-dettwyler — COMMENTED** [review]
+1

**Comment by wahmd** [comment]
lmao

**Comment by philipk19238** [comment]
LGTM

**Comment by 0xrpj** [comment]
LMFAO

**Comment by wahmd** [comment]
ROFL

**Comment by anthdono** [comment]
lgtm

**Comment by anthdono** [comment]
> lgtm

thanks, will merge

**Pull request closed without merging**
