### PR TITLE
fix scoreTweet algorithm

### PR DESCRIPTION
**Pull request by elhardoum**

### CODE REVIEW

**Comment by Ivaylo-Korakov** [comment]
LGTM!

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by Ben-random** [comment]
LGTM!

**Review by birante — COMMENTED** [review]
We could make it a little shorter 

`score = tweet.getText().toLowerCase().contains("elon") ? 0d : score;
`

**Comment by Lamby777** [comment]
> Cool! Check out https://securityinfinity.com Secure your website now
> 
> (We are also giving one time opportunity to hack us in 24 hours. Show your skills) (we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

kid named `wapdost`:

**Comment by DanyPell** [comment]
Yet another sad nerd 😭 trying to be funny :D

**Comment by Lamby777** [comment]
> Yet another sad nerd 😭 trying to be funny :D

cope

**Pull request closed without merging**
