### PR TITLE
Remove author_is_elon

### PR DESCRIPTION
**Pull request by al-yakubovich**
Request to remove author_is_elon

### CODE REVIEW

**Comment by kerolloz** [comment]
Duplicate of https://github.com/twitter/the-algorithm/pull/327

**Comment by alexxriv** [comment]
lol what was the use for this?

**Comment by randiaz95** [comment]
Consider looking at my PR about removing censorship, as Elon's bias may be censoring tweets.

https://github.com/twitter/the-algorithm/pull/345

**Comment by ktj** [comment]
LGTM

**Comment by twais** [comment]
:shipit:

**Comment by carolsvntos** [comment]
:shipit:

**Comment by eahrend** [comment]
Fixed in #138

**Pull request closed without merging**
