### PR TITLE
Deleted All bad practiced code

### PR DESCRIPTION
**Pull request by vitaminncpp**
- An Important PR.
- Removed all the code that is badly written

### CODE REVIEW

**Comment by mutexdeveloper** [comment]
LGTM

**Comment by notaduck448** [comment]
Did some benchmarks and found this PR will result in a 2000% boost in algorithm speed and should be merged immediately. It will be very good for elon musk and performance

**Comment by realmercy** [comment]
This PR fixed my depression

**Review by ayushtomar95 — COMMENTED** [review]
lgtm

**Review by chnnxyz — COMMENTED** [review]
lgtm

**Comment by junaga** [comment]
Imagine being funny

**Comment by ilovelinux** [comment]
Spam, please close.

**Comment by Kenchir** [comment]
NACK

**Review by vitaminncpp — COMMENTED** [review]
very good

**Pull request closed without merging**
