### PR TITLE
Feat: Improve build process and reduce code bloat by 33%

### PR DESCRIPTION
**Pull request by eahrend**
Make it exit 1 because 1 is larger (and therefore better than) 0

Also reducing lines of code by 33%

### CODE REVIEW

**Comment by dcow** [comment]
Please exit 2, because 2 is the only even prime number.

**Comment by eahrend** [comment]
@dcow 2 is twice as large as 1, and therefore takes up more memory. We're trying to optimize for performance here.

**Comment by eahrend** [comment]
@dcow 2 is twice as large as 1, and therefore takes up more memory. We're trying to optimize for performance here.

**Comment by Heliodex** [comment]
Duplicate of #23587012987199

**Comment by matthewdeanmartin** [comment]
Build script is really gotten out of hand, can we reduce line code count?

**Comment by eahrend** [comment]
> Build script is really gotten out of hand, can we reduce line code count?

Great idea. Will update

**Comment by eahrend** [comment]
@matthewdeanmartin reduced line count by 33%

**Pull request closed without merging**
