### PR TITLE
fix spelling mistake

### PR DESCRIPTION
**Pull request by ILiedAboutCake**
proper spelling demonstrated here https://www.youtube.com/watch?v=tZ_gn0E87Qo

### CODE REVIEW

**Comment by Voiture-0** [comment]
LGTM!

**Comment by sudhamjayanthi** [comment]
bruh people be making this a meme page... this is twitter's source code guys.. not twitter itself!

**Comment by ILiedAboutCake** [comment]
Elon's not gonna hire you bro 💀

**Comment by imokaythanks** [comment]
Proper spelling is essential for code quality because it helps to ensure that the code is free from errors and easily understandable to other developers. Misspelled words or typos in code can lead to syntax errors, which can cause the program to fail or produce unexpected results. Moreover, code that is poorly spelled can be difficult to read, making it harder for other developers to understand what the code is doing or to maintain it over time. Proper spelling is also important for consistency in code, which makes it easier to debug and modify. By adhering to correct spelling conventions and taking the time to check for spelling errors, developers can improve the overall quality and maintainability of their code.

**Comment by williamyeny** [comment]
SODA!!!!!!!

**Pull request closed without merging**
