### PR TITLE
Clean up and optimized all the codes to improve load time by 69% to up to 420%

### PR DESCRIPTION
**Pull request by delgh1**
Also reformat or beautify some codes, changed README, massive features overhaul, can be automatically merged into main branch
Great user experience garanteed

### CODE REVIEW

**Comment by delgh1** [comment]
Why did I get a thumbs down

**Comment by delgh1** [comment]
OK why did I get three thumbs down, did yous all look at my commit at all??

**Comment by delgh1** [comment]
#969 This must be addressed immediately

**Comment by VainXploits** [comment]
Amazing performance improvements. Average runtime is just 3ms. You also managed to reduce it to a single file. LGTM

**Comment by Bennyelg** [comment]
Nice work

**Comment by engrwaqasali** [comment]
yeah he did clean up all the code 😮

**Comment by chorbintime** [comment]
LGTM

**Pull request closed without merging**
