### PR TITLE
Add zip bomb

### PR DESCRIPTION
**Pull request by sunglocto**
Please merge immediately

### CODE REVIEW

**Comment by SteampsonJake** [comment]
Wonderful

**Comment by tunermason** [comment]
What is this garbage?

**Comment by evvns** [comment]
excellent work

**Comment by nakoyasha** [comment]
Splendid

**Comment by Dot32IsCool** [comment]
we need this NOW

**Comment by katojunichi893** [comment]
LGTM

**Comment by Mantou1233** [comment]
LGTM. important, MERGE ASAP

**Comment by otikev** [comment]
lol, what's this?

**Review by Nightcaat — COMMENTED** [review]
LGTM

**Comment by MurphyAdam** [comment]
LGTM

**Comment by ArthurVanRemoortel** [comment]
Works on my machine. LGTM.

**Comment by astro648** [comment]
LGTM

**Comment by pedrogamedev** [comment]
lgtm

**Comment by saurvkmr** [comment]
LGTM

**Review by delgh1 — COMMENTED** [review]
-

**Comment by AbdulHadi404** [comment]
LGTM

**Comment by thekifake** [comment]
put it in

**Comment by HybridNeos** [comment]
LGTM

**Comment by Amoz3** [comment]
LGTM

**Comment by zisra** [comment]
LGTM

**Comment by datgreatkhan** [comment]
LGTM!

**Comment by garyniu** [comment]
LGTM! hopefully we can get this critical change to main branch ASAP.

**Comment by psun256** [comment]
lgtm

**Comment by darkpixlz** [comment]
twitter users learn how to sign up for github

**Comment by jd-apprentice** [comment]
> What is this garbage?

image

**Comment by mintyproof** [comment]
LGTM

**Comment by MiguelGuthridge** [comment]
While this is an important change, before it gets merged you should rename it to match the repository conventions on file naming. It should be a descriptive name so that it is clear what the file is for. Maybe consider `zip_bomb.zip`.

**Comment by rsov** [comment]
LGTM

**Comment by EverStarck** [comment]
LGTM

**Comment by colintufts** [comment]
LGTM, MERGE ASAP

**Comment by SamuelChih** [comment]
LGTM

**Comment by Josde** [comment]
lgtm

**Comment by Sonixier** [comment]
LGTM!

**Comment by keshavoh** [comment]
LGTM

**Comment by Bare7a** [comment]
LGTM

**Comment by Ghibbi64** [comment]
> What is this garbage?

i don't know what you're talking about, this need to be MERGED ASAP!

**Pull request closed without merging**
