### PR TITLE
Modify has_gte_10k_favs to have the correct int

### PR DESCRIPTION
**Pull request by neoncrumpet**
Original was checking to >= 1000, changed to 10000

### CODE REVIEW

**Comment by Odas0R** [comment]
Lol! Good catch!

**Comment by KaleV-K** [comment]
Nice find

**Comment by delgh1** [comment]
We at the Twitter company thank you for your service and the company will compensate your time and effort for absolutely nothing. Please also print out the repository on A4 or letter-sized paper, bring them to the Twitter HQ.

**Comment by d33pfri3d** [comment]
@CLAassistant 

There is no CLA to sign for twitter/the-algorithm

**Pull request closed without merging**
