### PR TITLE
🛑URGENT🛑 Capitalize Tweet for consistency in README.md

### PR DESCRIPTION
**Pull request by slweeb**
Not every instance of the word "Tweet" was capitalized.

### CODE REVIEW

**Comment by lucasnethaj** [comment]
thank you for your service

**Comment by issamoxix** [comment]
lgtm

**Comment by alsonick** [comment]
LGTM

**Comment by GalvinPython** [comment]
lgtm

**Comment by hoangphuc05** [comment]
lgtm

**Comment by melon-husk** [comment]
lgtm

**Comment by brandondrew** [comment]
are you sure that the solution is to use upper case on all of them, rather than to use lower case on all of them?

**Comment by slweeb** [comment]
> are you sure that the solution is to use upper case on all of them, rather than to use lower case on all of them?

Yes, official Twitter style is to capitalize "Tweet", such as in the Help Center: https://help.twitter.com/en/using-twitter/how-to-tweet

**Comment by hoangphuc05** [comment]
I think we should lowercase all "Tweet" in the Help Center instead

**Comment by slweeb** [comment]
> I think we should lowercase all "Tweet" in the Help Center instead

It's not just the Help Center, it's every Twitter article ever, it's the standard.

**Comment by brandondrew** [comment]
> > are you sure that the solution is to use upper case on all of them, rather than to use lower case on all of them?
> 
> Yes, official Twitter style is to capitalize "Tweet", such as in the Help Center: https://help.twitter.com/en/using-twitter/how-to-tweet

In that case I support your PR

**Comment by slweeb** [comment]
why was this closed? not fixed

**Comment by hoangphuc05** [comment]
I told you, the correct direction is to lowercase “tweet” everywhere else. Closing this PR since the fix does not address the root cause

**Pull request closed without merging**
