### PR TITLE
Fixed it 

### PR DESCRIPTION
**Pull request by XXbruhmanXX**
https://twitter.com/rekdacted

### CODE REVIEW

**Review by jamesthesnake — COMMENTED** [review]
This guy gets it ! LGTM

**Comment by rekdacted** [comment]
your welcome guys

**Comment by HyflerSD** [comment]
I mean there's a lot less code to compile so this should be amazingly fast!

**Comment by rekdacted** [comment]
FGGlZPgXEAsmvia

**Comment by RinLovesYou** [comment]
Please provide a clear reason for closing this?

**Comment by rekdacted** [comment]
> 

+1

**Pull request closed without merging**
