### PR TITLE
Can u pwease merge my pwull wequest senpai?!! UwU

### PR DESCRIPTION
**Pull request by anabastos**
Hii~

I fixie wixied the JSON-api fucksy wucksie!!!! xpp

I repwaced the `Prototypes.func` wiff a more ~ streamylined ~ kawaii `Pwototypiee.funkywunks` object that make the JS go sooper dooper fest!! XD * starts twerking*

Can u pwease merge my pwull wequest senpai?!! UwU

### CODE REVIEW

**Comment by Lamby777** [comment]
We need this immediately. LGTM

**Review by aelnonym — COMMENTED** [review]
This should be the top priority. LGTM

**Review by mathenls — COMMENTED** [review]
LGTM
Should go to prod immediatelly

**Comment by ninetynin** [comment]
lmaooo

**Comment by ShockAwer** [comment]
LGTM
Definitely top priority stuff

**Comment by MattheusHenrique** [comment]
LGTM!!!!!!!

**Comment by yordadev** [comment]
LGTM ✔️

**Comment by sidarkelse** [comment]
LGTM 🤣

**Comment by lustfaS** [comment]
Uwu 👍🏻 LGTM

**Comment by nickkxsper** [comment]
LGTM

**Comment by LulianoM** [comment]
LGTM uwu

**Comment by anurag-roy** [comment]
LuGwTuM!
MOREmoji_uwu svg

**Comment by igorcaldeira** [comment]
lgtm

**Review by anurag-roy — COMMENTED** [review]
uWu

**Comment by Jstinii** [comment]
LGTM

**Comment by mateussmohamed** [comment]
LGTM

**Comment by shyvesCCD** [comment]
LGTM

**Comment by pauloendoh** [comment]
LGTM!! *starts twerking aggressivelly*

**Comment by miguel-nascimento** [comment]
>www naisu jobuwu

**Comment by mistervaibhav** [comment]
what in the name of fuck

**Comment by algebraic-sofia** [comment]
uwu

**Comment by Lamby777** [comment]
closed? dang, literally 1984

**Comment by devssauro** [comment]
IT'S EXTREMELY NECESSARY TO BE MERGED.

**Comment by george124816** [comment]
LGTM

**Comment by Nick-Gabe** [comment]
so much 1984, its a read-only open source uh???

**Comment by marcoslor** [comment]
It's Friday night, a gr8 day to merge this.

**Comment by phiter** [comment]
Screenshot_20230331_214157_Chrome

**Comment by Lamby777** [comment]
> so much 1984, its a read-only open source uh???

yes, any time period after the moment this PR got closed is literally worse than 1984

**Comment by Kineforce** [comment]
i think that's a pretty reasonable change, please merge immediately to prod!

**Comment by otikev** [comment]
Closed open-source

**Comment by mechamobau** [comment]
LGTM 🎉

**Comment by andriycraft** [comment]
Why did they close it :(

**Pull request closed without merging**
