### PR TITLE
optimized the algorithm

### PR DESCRIPTION
**Pull request by csapanski**
took care of some backend optimizations to increase algorithm workflow

### CODE REVIEW

**Comment by claudiodekker** [comment]
Duplicate of #809

**Comment by Killjoyer** [comment]
Thanks for the contribution! 
But i think your code lacks tests

**Comment by TheRealDeLorian** [comment]
You're hilarious. everyone loves you and thinks you're so funny

**Comment by Y2KForever** [comment]
LGTM 🔥

**Comment by aldy97** [comment]
LGTM

**Comment by ryanmattos** [comment]
It seems to work for me

**Comment by dzikrisyairozi** [comment]
image

**Comment by Cosmelon** [comment]
> Thanks for the contribution! But i think your code lacks tests

Thanks for the feedback, I added further optimizations to make the need for tests unnecessary.

**Comment by nobodyindustries** [comment]
image

**Comment by poleshe** [comment]
LGTM

**Comment by sandip2224** [comment]
LGTM sir!

**Comment by kadeksuryam** [comment]
What a bunch of kids

**Comment by delgh1** [comment]
LGTM

**Comment by Cosmelon** [comment]
You know, I'm still looking through some of the code I've re-written, and come to think of it I actually have further progress to make, will be updating as I fix.

**Comment by ScribbleDribble** [comment]
LGTM

**Comment by rdnsyh** [comment]
bug free code, ship it!! 🚀🚀

**Comment by leonidlist** [comment]
LGTM

**Comment by SaltfishAmi** [comment]
lgtm

**Comment by nnaem** [comment]
LGTM

**Comment by ANormalProgrammer** [comment]
LGTM

**Comment by parnexcodes** [comment]
LGTM

**Comment by kyeboard** [comment]
LGTM

**Comment by wolfvandenbussche** [comment]
LGTM

**Comment by kdata12** [comment]
LGTM

**Comment by ZeroDiscord** [comment]
LGTM

**Review by Brendan5536 — COMMENTED** [review]
Great work. Can’t seem to find any bugs.

**Comment by pgh268400** [comment]
Code stripping is a great optimization technique

**Comment by helderpgoncalves** [comment]
Took some time to review it. But yes LGTM!

**Review by xkstndua15 — COMMENTED** [review]
LGTM 🔥

**Comment by happytalkSU** [comment]
LGTM

**Comment by gokayumutlu** [comment]
I am sure It would run instantly just like there is nothing to compile after these changes.

**Comment by wodnjse** [comment]
LGBT

**Comment by Default-Box** [comment]
LGTM

**Comment by ashleyirispuppy143** [comment]
LGTM, idk why its still not merged tho

**Comment by mm12** [comment]
LGTM

**Pull request closed without merging**
