### PR TITLE
Remove censorship outside of adult content

### PR DESCRIPTION
**Pull request by randiaz95**
Censorship, the act of suppressing or controlling information, is detrimental to a healthy and democratic society. The freedom of expression and access to information are fundamental human rights that should be protected and encouraged. When censorship is imposed, it stifles diverse viewpoints, hinders creativity, and prevents the dissemination of important information that can lead to positive change. It can also lead to a lack of accountability, as those in power may hide information to avoid scrutiny or criticism. Ultimately, censorship undermines the democratic principles of transparency and accountability, limits our ability to learn and grow, and threatens the foundation of a free and open society.

This change only allows adult content to be considered offensive; thereby removing big brother.

### CODE REVIEW

**Review by datkat21 — COMMENTED** [review]
LGTM

**Comment by anurag-roy** [comment]
d8f66d222a6e7a670c02af9d89a2d70e2c8881a101f5ab347a695649382bf352_1

**Comment by randiaz95** [comment]
Consider this TLDR: This change only allows adult content to be considered offensive; thereby removing big brother.

**Comment by anurag-roy** [comment]
Thanks for the tldr @randiaz95, makes sense now! LGTM!

**Comment by paulbauriegel** [comment]
Filtering offensive topics is not a bad thing and has nothing to do with censorship from my point of view. The problem is that the text files are not open sourced, so anything could be written in them, but from that perspective you could also put your "censorship terms" into the adult_tokens.txt ...

**Comment by randiaz95** [comment]
Yes, and that would be explicit censorship by putting non adult_tokens into the adult_tokens file.

Whereas now they can get away with it.

**Comment by Lucretiel** [comment]
This change also causes even adult tokens to be ignored if they appear in usernames / display names

**Comment by randiaz95** [comment]
If you look at the `isUserNameOffensive` method: Adult tokens were never being checked here for username, I can update to use the adult filter on the usernames instead though.

We should consider adult tokens being bad in usernames, if you search an adult token word in twitter you will get some crazy/raunchy stuff I likely don't think we will ever be able to filter.

**Comment by randiaz95** [comment]
Closing this PR as I don't get paid to work for twitter.

Just use this as proof that we are being censored.

**Comment by paulbauriegel** [comment]
I think filtering offensive content is not censorship, you are also beeping out all the f***s in american sitcoms

**Comment by randiaz95** [comment]
> I think filtering offensive content is not censorship, you are also beeping out all the f***s in american sitcoms

Actually thats why I bumped the max offensive terms limit to 3, so we can still write "You F***ing *sshole"

Maybe if we can see a peepee going in a vajaijai with a simple twitter search we shouldn't censor things the FBI wants us to censor.

**Pull request closed without merging**
