### PR TITLE
Removes all java files

### PR DESCRIPTION
**Pull request by Nick-Gabe**
we need twitter to run faster

### CODE REVIEW

**Comment by StevenCurran** [comment]
What is this garbage

**Comment by danielmelogpi** [comment]
Checks are green, LGTM

**Comment by AmrAhmedA** [comment]
This is clean stuff, ship it.

**Comment by aalmeida00** [comment]
seems good. 

✅

**Comment by daviegourevitch** [comment]
LGTM 👍

**Comment by vbkaisetsu** [comment]
It would better to remove all Python files, not Java files.
Screenshot_20230401-104529~2

https://greenlab.di.uminho.pt/wp-content/uploads/2017/09/paperSLE.pdf

**Pull request closed without merging**
