### PR TITLE
✏️❗️ fix: add missing dots to 'i.e.' and 'e.g.', grammar

### PR DESCRIPTION
**Pull request by moskalakamil**
## Description
- [x] Add missing dots for *every* `i.e.`.
- [x] Add missing dots for *every* `e.g.`.
- [x] Improve grammar in `simclusters-ann/README.md`.
- [x] Remove unnecessary break lines in `simclusters-ann/README.md`.

### CODE REVIEW

**Comment by cyanblock** [comment]
crucial fix

**Comment by kerolloz** [comment]
Duplicate of https://github.com/twitter/the-algorithm/pull/295

**Comment by anurag-roy** [comment]
Bro needed 5 people for this 💀

**Comment by moskalakamil** [comment]
> Bro needed 5 people for this 💀

to be sure ;)

**Review by skavierin — COMMENTED** [review]
LGTM 💯 💯 💯

**Pull request closed without merging**
