### PR TITLE
Make the world slightly less annoying

### PR DESCRIPTION
**Pull request by solidiquis**
### Changes

- Deleted entire source code to make the world slightly less annoying
- Completely eliminated memory usage and CPU utilization to mitigate the entrapment of heat by the abundance of green-house gases in our atmosphere to fight global climate change 💪

### To-Do

- [ ] Get lunch

### CODE REVIEW

**Comment by anurag-roy** [comment]
@solidiquis Lunch on me today

**Comment by atticusliu** [comment]
LGTM

**Comment by solidiquis** [comment]
Waiting for Mr. Musk to approve

**Review by ChrisHammond — COMMENTED** [review]
If only

**Review by anurag-roy — COMMENTED** [review]
GGs

**Comment by deviant-semicolon** [comment]
LGTM

Waiting for your approval Elon 🙏

**Comment by scentre** [comment]
lol

**Comment by fjdklsakhirluyterlg** [comment]
Not good enough, at twitter we require negative cpu usage to drain greenhouse gases

**Comment by zubyCharles** [comment]
I would like to know the rationale behind this rather impactful PR.

**Comment by LunarFang416** [comment]
LGTM

**Review by blaze-dot — COMMENTED** [review]
I approve

**Comment by solidiquis** [comment]
@CLAassistant pls advise

Screen Shot 2023-03-31 at 4 16 11 PM

**Pull request closed without merging**
