### PR TITLE
420 - Make numbers more accurate

### PR DESCRIPTION
**Pull request by Jamesbarford**

### CODE REVIEW

**Comment by sunglocto** [comment]
LGTM

**Comment by ndrezn** [comment]
how does this affect performance?

**Comment by Jamesbarford** [comment]
> how does this affect performance?

Improves it by 69%

**Comment by GalvinPython** [comment]
> > how does this affect performance?
> 
> Improves it by 69%

nice improvement - lgtm

**Comment by AngelofVerdant** [comment]
I come not to partake in the violence but only to watch it unravel🤣🤣🤣🤣

**Comment by WittyKE** [comment]
How does this algorithm really work

**Comment by IbrahimCSAE** [comment]
🤣🤣🤣

**Comment by Lamby777** [comment]
this has got to be the single best use case for regex in an IDE's "search and replace" function

**Pull request closed without merging**
