### PR TITLE
feat: save dozens of kilobytes of space by minifying all python

### PR DESCRIPTION
**Pull request by abhiaagarwal**

### CODE REVIEW

**Comment by SammCheese** [comment]
Horrible Idea, especially for readability. smh smh

**Comment by kerolloz** [comment]
Elon will definitely thank you for saving him a few bucks.

**Comment by PickleNik** [comment]
image

**Comment by abhiagarwal01** [comment]
@SammCheese

**Review by moskalakamil — COMMENTED** [review]
where prettier????

**Comment by Robxon** [comment]
LGTM

**Comment by kibrukuture** [comment]
who is going to read spaghetti code base later?

**Comment by samoshan** [comment]
Elon hire this man 😤😤

**Comment by danielamar101** [comment]
LGTM ship it ASAP

**Comment by AlexPerathoner** [comment]
Deleting more lines than you added? Doesn't sound like a productive developer!

**Comment by vikgomat** [comment]
Donno why I'm craving some pasta after reviewing this code.

LGTB!!!

**Pull request closed without merging**
