### PR TITLE
algorithm edits

### PR DESCRIPTION
**Pull request by znwhite**

### CODE REVIEW

**Comment by murosev** [comment]
LGTM

**Comment by hickatheworld** [comment]
LGTM

**Comment by FathiQ** [comment]
LGTM

**Comment by monsterofhell** [comment]
Lame. Done by many by now.

**Comment by plondon** [comment]
utACK

**Comment by mutexdeveloper** [comment]
LGTM

**Comment by Lamby777** [comment]
Not enough orange crabs. I'm afraid I'd have to rate this code as 🚀 BLAZINGLY 🚀 SLOW 🚀 but other than that it looks good.

**Comment by IsraPerez98** [comment]
LGTM

**Comment by MavethGH** [comment]
LGTM

**Comment by RomanTurner** [comment]
LGTM

**Comment by cstlh** [comment]
LGTM

**Comment by SurgicalSteel** [comment]
LGTM 🤘

**Review by mathenls — COMMENTED** [review]
No code = no bugs
LGTM

**Comment by krthr** [comment]
LGTM

**Comment by lustfaS** [comment]
👆🏻👉🏻 lgtm

**Comment by iacapuca** [comment]
lgtm

**Review by devssauro — COMMENTED** [review]
LGTM

**Comment by isamed92** [comment]
lgtm

**Comment by dmdutra** [comment]
thanks for your contribution
LGTM

**Comment by luciansr** [comment]
less code, less bugs. thanks for contributing to the complete removal of bugs from the algorithm 
and major rewrite our leadership is so much looking forward to

LGTM

**Pull request closed without merging**
