### PR TITLE
Pull request in queue to be printed.

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
image

Ready for your review Elon!!!

### CODE REVIEW

**Comment by lukeify** [comment]
Hi @IbrahimCSAE—we don't have the budget for color ink at this point. Going forward, please be more considerate of Twitter office equipment in the future.

**Comment by IbrahimCSAE** [comment]
> Hi @IbrahimCSAE—we don't have the budget for color ink at this point. Going forward, please be more considerate of Twitter office equipment in the future.

Understood, only black and white going forward.

**Comment by EbenezerGH** [comment]
Please include tests!

**Comment by IbrahimCSAE** [comment]
> Please include test for portrait and landscape mode prints!

image

Done, please approve.

**Pull request closed without merging**
