### PR TITLE
Updating README to correct missing period.

### PR DESCRIPTION
**Pull request by HackTheMainframe**
I noticed a missing period, so I fixed it.

### CODE REVIEW

**Comment by slweeb** [comment]
lgtm

**Comment by AbdulMalikDev** [comment]
The most useful PR yet. This is exactly why twitter open-sourced the code.

**Comment by sunglocto** [comment]
LGTM - the code will run 2000% faster with this PR

**Comment by IsraPerez98** [comment]
intersting

**Pull request closed without merging**
