### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VivanVatsa**
Hi There, I am a data scientist.

Made some tweaks in the Documentation. Added some clear Instructions for Twitter community!

### CODE REVIEW

**Comment by hoangphuc05** [comment]
Worked really hard to have your name in the list there

**Comment by hoangphuc05** [comment]
Some breaking changes here, I think we need more testing

**Comment by Anvil-Late** [comment]
Please change massive commits like this into more atomic commits

**Comment by ianfife** [comment]
Most useful data scientist

**Pull request closed without merging**
