### PR TITLE
Remove Elon bias

### PR DESCRIPTION
**Pull request by streibeb**

### CODE REVIEW

**Comment by byronbytes** [comment]
looks good to me

**Comment by Sethback** [comment]
Only used for stats. Whats the problem exactly?

**Comment by JustZeus** [comment]
Looks fine to me, approved

**Comment by primalmotion** [comment]
Can't you just "Remove Elon." ?

**Comment by Jucojo** [comment]
Need more cowbell, but approved

**Comment by brandon10003** [comment]
LGTM!!!!

**Comment by EthanPlant** [comment]
LGTM

**Comment by SunilRumbaLama** [comment]
we already have a lot of PRs suggesting that. I recommend looking into the earlier commits from users.

**Comment by SeizureSaladd** [comment]
LGTM

**Comment by Vutlhari** [comment]
LGTM

**Comment by grafail** [comment]
LGTM

**Review by 0xJepsen — COMMENTED** [review]
LGTM!

**Comment by victorlukinha** [comment]
LGTM

**Comment by Arisenby** [comment]
LGTM

**Comment by benjaminaheath** [comment]
LGTM

**Comment by puskuruk** [comment]
LGTM! Just ship it 🍻

**Pull request closed without merging**
