### PR TITLE
Replaced the source code with Super Mario 64

### PR DESCRIPTION
**Pull request by RatserX**
The Super Mario Bros. Movie just released, and the algorithm is using the same old code? This is absurd.
Here, take the Super Mario 64 source code instead and go celebrate!

### CODE REVIEW

**Comment by wiichicken** [comment]
legend for **actually** replacing it with the real source code

**Comment by LiamChat** [comment]
I believe that this will change twitter for the better

**Comment by uzbeki** [comment]
a little funny, but lameeeeeeee

**Comment by mylesbartlett72** [comment]
> I believe that this will change twitter for the better

yeah this would finally kill the birdsite when Nintendo DMCAs them into nonexistence

**Pull request closed without merging**
