### PR TITLE
Delete Twitter

### PR DESCRIPTION
**Pull request by sunglocto**
This is for the greater good.

### CODE REVIEW

**Comment by stickfab** [comment]
LGTM

**Comment by HyflerSD** [comment]
What is the time/space complexity of this implementation?

**Comment by highnet** [comment]
LGTM

**Comment by XXbruhmanXX** [comment]
Please review [this](https://github.com/twitter/the-algorithm/pull/114)

**Comment by sunglocto** [comment]
> What is the time/space complexity of this implementation?

I don't know what this means, I am working for Twitter and get paid 5 cents an hour
Code is now blazingly fast though, i think

**Comment by SivkovSavely** [comment]
> What is the time/space complexity of this implementation?

@HyflerSD it's so complex that it warps the space-time continuum and creates a black hole once merged.

**Comment by GalvinPython** [comment]
lgtm

**Comment by Marcellofabrizio** [comment]
lgtm

**Comment by anthuanvasquez** [comment]
LGTM

**Comment by dlaufer** [comment]
Can this be done in Qbasic?

**Comment by OneAndonlyFinbar** [comment]
Lgtm, deploying to prod

**Comment by lucasassisrosa** [comment]
LGTM

**Comment by sunglocto** [comment]
NOOOOOO!

**Comment by Redeem-Grimm-Satoshi** [comment]
Reasons like this is why we don't make things open source!

**Comment by stickfab** [comment]
1984

**Comment by SeymoreBiggins** [comment]
LGTM 👍

**Comment by Debagnik** [comment]
Looks good to me

**Comment by Reeceeboii** [comment]
LGTM

**Comment by josphatmwania** [comment]
Interesting.

**Comment by ItsAstronomical** [comment]
lgtm

**Review by umutbasal — COMMENTED** [review]
LGTM

**Comment by rahmanharoon** [comment]
LGTM

**Comment by BarasaJnr** [comment]
LGTM

**Comment by hellofaizan** [comment]
> Reasons like this is why we don't make things open source! 

Ah it's just Sarcastic PR.

**Comment by yrdzrfxndfvh** [comment]
Looking into this.

**Comment by Romejanic** [comment]
this can't be merged fast enough

**Comment by jordanbertasso** [comment]
lgtm

**Comment by argahutama** [comment]
LGTM!

**Comment by Airdel** [comment]
lgtm 🤙

**Comment by kururuchan** [comment]
LGTM

**Comment by DenizOzii** [comment]
idk why this was closed but LGTM

**Comment by chixPL** [comment]
LGTM, ship it

**Comment by stingalleman** [comment]
lets goo

**Review by JakeyWasTaken — COMMENTED** [review]
LGTM not sure why this was closed

**Comment by d0nker420** [comment]
LGTM

**Comment by ektedar** [comment]
> Reasons like this is why we don't make things open source!

Allow transparency so people have insight on how Twitter functions and eventually build trust and eliminate bias ❌
Not take a joke ✅

**Comment by turrnut** [comment]
delete twitter LMAO

**Comment by ddvdozuki** [comment]
LGTM Ship it!

**Comment by L33Z22L11** [comment]
LGTM XD

**Comment by okaits** [comment]
LGTM, merge it

**Comment by okaits** [comment]
LGTM, merge it

**Comment by Laureatus** [comment]
LGTM

**Comment by turrnut** [comment]
pls merge

**Comment by 5GVckyy** [comment]
LGTM

**Comment by MotWnb** [comment]
LGTM

**Pull request closed without merging**
