### PR TITLE
Update SpaceSafetyLabelType.scala

### PR DESCRIPTION
**Pull request by danielhaim1**
Summary
=======

This content provides an overview of the Visibility Filtering algorithm and its types, which represent different characteristics of content that may pose a risk or harm to users to support legal compliance, improve product quality, and increase user trust through different remediations.

The algorithm utilizes three primary concepts: `SafetyLevel` `SafetyLabel` and `SafetyLabelType` It also defines several safety label types that can be grouped into three categories: _Content Classification_, _Content Moderation_, and _Status_. 

This article further explains the `UkraineCrisisTopic` safety label type, and its removal from the list of defined categories, the language used in the code which is not politically correct, and addresses recent staff cuts in Twitter's Trust and Safety and Global Content Moderation team which may hinder the review and action of flagged tweets.

Update (April 6th, 2023)
==================

As of April 5th, 2023, the changes discussed in this article [have been merged](https://github.com/twitter/the-algorithm/commit/3f6974687f0c16923da7e27b2c467abd0a109a1c) into the Visibility Filtering algorithm. The safety label type `UkraineCrisisTopic` has been removed from the code, and the categorization of safety label types has been updated to ensure consistency and accuracy.

I would like to thank everyone for their contributions and effort in getting this pull request merged, and I hope these changes will help improve the safety and trust of Twitter's platform for all users. Your effort and dedication have been instrumental in making these changes possible, and I am honored to be a part of such a supportive and collaborative community.

Visibility Filtering
=============

Visibility Filtering is a rule engine that centrally instructs the client on adjusting the display of specific content at read time. This library is responsible for _"filtering content to support legal compliance, improve product quality, increase user trust, protect revenue through hard-filtering, visible product treatments, and coarse-grained downranking"_.

### Types

The library utilizes three primary concepts to support this:

* `SafetyLevel`: represents the context in which content is viewed
* `SafetyLabel`: identifies content as potentially harmful
* `SafetyLabelType` specifies the type of policy violation
* `SpaceSafetyLabelType` groups safety labels based on content characteristics

### Categories

It is possible to logically categorize them into three groups:

1. **Content Classification**
   * `CoordinatedHarmfulActivityHighRecall`
   * `HatefulHighRecall`
   * `ViolenceHighRecall`
   * `CivicIntegrityMisinfo`
   * `MedicalMisinfo`
   * `GenericMisinfo`
   * `MisleadingHighRecall`
   * `NsfwHighPrecision`
   * `NsfwHighRecall`
   * `UntrustedUrl`
2. **Content Moderation**
   * `DoNotAmplify`
   * `DoNotPublicPublish`
   * `DmcaWithheld`
   * `HighToxicityModelScore`
3. **Status**
   * `Deprecated`
   * `Unknown`

The safety label `UkraineCrisisTopic` [on line 39](https://github.com/twitter/the-algorithm/blame/ec83d01dcaebf369444d75ed04b3625a0a645eb9/visibilitylib/src/main/scala/com/twitter/visibility/models/SpaceSafetyLabelType.scala#L39) is an outlier to the categorization because it does not fit into any defined category.

Moreover, the term _"crisis"_ is not similar to the other safety label types defined in the code. While the other safety label types refer to specific characteristics of content that may pose a risk or harm to users, _"crisis"_ is a broader term that refers to a situation or event that poses a significant challenge or threat to individuals, organizations, or communities. 

Conclusion
========

As a result, I propose to remove `UkraineCrisisTopic` from the code. This change helps maintain consistency in categorizing safety label types and ensures that all labels have specific characteristics that may pose a risk or harm to users.

Content Moderation
===============

The safety label type `UkraineCrisisTopic` represents a specific safety label designed to flag content related to the ongoing war in Ukraine. 

When a tweet is flagged with this safety label, it indicates that the tweet's content is related to the topic, and tweets with this label may undergo additional review or may be excluded from specific features, such as trending topics.

Moreover, the language used in the code is not politically correct, which may offend some users. Additionally, with recent staff cuts in Twitter's Trust and Safety and Global Content Moderation team, it is unclear whether these flagged tweets are being reviewed and actioned.

Reference in Code
==============

[s.SpaceSafetyLabelType.UkraineCrisisTopic -> UkraineCrisisTopic](https://github.com/twitter/the-algorithm/blame/ec83d01dcaebf369444d75ed04b3625a0a645eb9/visibilitylib/src/main/scala/com/twitter/visibility/models/SpaceSafetyLabelType.scala#L39)

```java
s.SpaceSafetyLabelType.DoNotAmplify -> DoNotAmplify,
s.SpaceSafetyLabelType.CoordinatedHarmfulActivityHighRecall -> CoordinatedHarmfulActivityHighRecall,
s.SpaceSafetyLabelType.UntrustedUrl -> UntrustedUrl,
s.SpaceSafetyLabelType.MisleadingHighRecall -> MisleadingHighRecall,
s.SpaceSafetyLabelType.NsfwHighPrecision -> NsfwHighPrecision,
s.SpaceSafetyLabelType.NsfwHighRecall -> NsfwHighRecall,
s.SpaceSafetyLabelType.CivicIntegrityMisinfo -> CivicIntegrityMisinfo,
s.SpaceSafetyLabelType.MedicalMisinfo -> MedicalMisinfo,
s.SpaceSafetyLabelType.GenericMisinfo -> GenericMisinfo,
s.SpaceSafetyLabelType.DmcaWithheld -> DmcaWithheld,
s.SpaceSafetyLabelType.HatefulHighRecall -> HatefulHighRecall,
s.SpaceSafetyLabelType.ViolenceHighRecall -> ViolenceHighRecall,
s.SpaceSafetyLabelType.HighToxicityModelScore -> HighToxicityModelScore,
// s.SpaceSafetyLabelType.UkraineCrisisTopic -> UkraineCrisisTopic,
s.SpaceSafetyLabelType.DoNotPublicPublish -> DoNotPublicPublish,
```
[case object UkraineCrisisTopic extends SpaceSafetyLabelType](https://github.com/twitter/the-algorithm/blame/ec83d01dcaebf369444d75ed04b3625a0a645eb9/visibilitylib/src/main/scala/com/twitter/visibility/models/SpaceSafetyLabelType.scala#L72)

```java
case object DoNotAmplify extends SpaceSafetyLabelType
case object CoordinatedHarmfulActivityHighRecall extends SpaceSafetyLabelType
case object UntrustedUrl extends SpaceSafetyLabelType
case object MisleadingHighRecall extends SpaceSafetyLabelType
case object NsfwHighPrecision extends SpaceSafetyLabelType
case object NsfwHighRecall extends SpaceSafetyLabelType
case object CivicIntegrityMisinfo extends SpaceSafetyLabelType
case object MedicalMisinfo extends SpaceSafetyLabelType
case object GenericMisinfo extends SpaceSafetyLabelType
case object DmcaWithheld extends SpaceSafetyLabelType
case object HatefulHighRecall extends SpaceSafetyLabelType
case object ViolenceHighRecall extends SpaceSafetyLabelType
case object HighToxicityModelScore extends SpaceSafetyLabelType
// case object UkraineCrisisTopic extends SpaceSafetyLabelType
case object DoNotPublicPublish extends SpaceSafetyLabelType
```

### CODE REVIEW

**Comment by danielhaim1** [comment]
Why was this closed @maksimru ?

**Comment by danielhaim1** [comment]
Visibility Filtering is a rule engine that centrally instructs Twitter clients on how to adjust the display of certain Twitter content at read time. The library filters Twitter content to support legal compliance, improve product quality, **increase user trust**, **protect revenue through hard-filtering**, **visible product treatments**, and **coarse-grained downranking**.

To support this, Visibility Filtering utilizes three primary concepts: `SafetyLevel`, `SafetyLabel`, and `SafetyLabelType`.

- `SafetyLevel`: represents the product context in which the Viewer is requesting to view the Content (e.g. Timeline, Profile).
- `SafetyLabel`: associates with tweet, user, direct message, media, space, etc. as a primary labeling mechanism for Safety. Safety labels enable different remediations such as applying a `SafetyLabel` that results in tweet interstitial or notice.
- `SafetyLabelType`: describes a specific policy violation for a given noun instance and usually leads to reduced visibility of the labeled entity in product surfaces.

In this context, `UkraineCrisisTopic` is a `SpaceSafetyLabelType` that represents a specific safety label designed to flag content related to the ongoing war in Ukraine. When a tweet is flagged with the `UkraineCrisisTopic` safety label, it indicates that the tweet's content is related to the "_crisis_" in Ukraine. For example, tweets with this safety label may undergo additional review or may be excluded from certain features, such as trending topics.

According to [this article](https://www.bloomberg.com/news/articles/2023-01-07/elon-musk-cuts-more-twitter-staff-overseeing-content-moderation#xj4y7vzkg), most of the Global Content Moderation team has been let go.

So are these auto-flagged tweets sitting idle without moderation?

Regardless, the analysis above suggested that the `SafetyLabelType` `UkraineCrisisTopic` is an outlier for this categorization because it does not fit into any of the categories of Safety.

Furthermore, the term "crisis" is not similar to the other safety label types defined in the code. While the other safety label types refer to specific characteristics of content that may pose a risk or harm to users, "crisis" is a broader term that refers to a situation or event that poses a significant challenge or threat to individuals, organizations, or communities.

**Comment by maksimru** [comment]
There are a lot of speculations around this, so let's keep it opened and use for **technical discussions**. **Space**SafetyLabelType is safety label designed for "Spaces". It is not related to tweets. More over, there are no rules in the VF library as you see that are based on this label: https://github.com/twitter/the-algorithm/search?q=UkraineCrisisTopic. See more examples in https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/visibilitylib/src/main/scala/com/twitter/visibility/rules/SpaceRules.scala

**Comment by maksimru** [comment]
Summarizing above point, there is no impact from this label on nor spaces, nor tweets. However, I see your point that it might be good to remove it, just to avoid any future speculations, and confusion

**Comment by danielhaim1** [comment]
> Summarizing above point, there is no impact from this label on nor spaces, nor tweets. However, I see your point that it might be good to remove it, just to avoid any future speculations, and confusion

I wholeheartedly agree.

**Comment by webknjaz** [comment]
> Why was this closed

I'd assume that the answer is in their profile. The person is russian 🤷‍♂️

**Comment by danielhaim1** [comment]
> > Why was this closed
> 
> I'd assume that the answer is in their profile. The person is russian 🤷‍♂️

I strongly suggest conducting additional research prior to making such statements. It's simple to pass a hasty judgment, but he has consistently advocated for Ukraine. Moreover, this may not be the appropriate platform to delve into this topic in any detail.

**Comment by webknjaz** [comment]
> I strongly suggest conducting additional research prior to making such statements. It's simple to pass a hasty judgment, but he has consistently advocated for Ukraine.

@danielhaim1 agreed. Though, in my experience, they don't hesitate having contradictory ideas. Having seen this specific action and a few typical markers I jumped to conclusions.

So, I took your advice and looked deeper. Unfortunately, I wasn't surprised much by what I've witnessed: the individual's support statements peacefully co-exist with the rhetoric of the so-called "russian opposition". Said "opposition" is well known to exhibit the same imperialist ambitions and colonialist apologism as the rest of the population, sadly. This bit specifically, is the opposite of supporting Ukraine, even though it might seem different to an unprepared reader.
While some of the actions seem to advocating for Ukraine, the general impression is not as optimistic.

That said, I we can't conclude that the person's views didn't influence this specific instance of behavior.

> Moreover, this may not be the appropriate platform to delve into this topic in any detail.

I think the place is wherever the behavior happens. If nobody advocated against the use of the racist language in code, we'd keep having whitelisted masters and blacklisted slaves in many more software projects. But somebody did point out that this is bad and kept explaining what's bad about it until the change started to be accepted.
So why can't I be questioning the motivation of actions related to using toxic misleading language that directly affects the people of Ukraine? Can I at least ask not to minimize the experiences of my compatriots in code?

**Comment by danielhaim1** [comment]
Thank you for sharing your perspective on this issue @webknjaz. I appreciate your input, and I believe that we can work together to find a solution that eliminates harmful language from the codebase and maintains an inclusive and respectful environment for everyone involved.

Let's stay focused on the technical aspects of this problem and collaborate to find the best solution to get this merged as soon as possible.

**Comment by 5HT** [comment]
There is no technical aspect of the problem. Labeling this as Ukrainian Crisis is a russian PsyOps against the future of all Ukrainians by imprinting this into such a discussion. Disgusting.

**Comment by mptorz** [comment]
> Summarizing above point, there is no impact from this label on nor spaces, nor tweets. However, I see your point that it might be good to remove it, just to avoid any future speculations, and confusion

Is there any reason not to remove it? If there is then at least it should be renamed, because it is misleading and inappropriate. The label refers to the Russian invasion of Ukraine. I will make PR so we can fix it ASAP.

**Comment by mptorz** [comment]
Let's rename it to `RussianInvasionOfUkraineTopic` for the time being. I created a pull request here I created a pull request here https://github.com/twitter/the-algorithm/pull/1659

**Comment by mptorz** [comment]
@maksimru Let's rename it to `RussianInvasionOfUkraineTopic` for the time being. I created a pull request here I created a pull request here https://github.com/twitter/the-algorithm/pull/1659

**Pull request closed without merging**
