### PR TITLE
Removed Elon Musk from hydrator

### PR DESCRIPTION
**Pull request by Abastien1734**
removed Elon from the hydrator for tweets

### CODE REVIEW

**Comment by escaman22** [comment]
Looks good to me 👍

**Comment by csubj** [comment]
this is just for stats, really. but LGTM lol

**Comment by myConsciousness** [comment]
LGTM! 👍

**Comment by eahrend** [comment]
Duplicate of #138

**Comment by mm12** [comment]
pls merge fast

**Pull request closed without merging**
