### PR TITLE
feat: add more political bias

### PR DESCRIPTION
**Pull request by TheLDB**
we're already partially there lets go full in

Adds bias for libertarian party, green party, AND independents!

### CODE REVIEW

**Review by neverabsolute — COMMENTED** [review]
LGTM

**Comment by etdr** [comment]
LGTM

**Comment by dhikshith12** [comment]
LGTM

**Review by yma010 — COMMENTED** [review]
LGTM

**Review by etdr — COMMENTED** [review]
Looks good to me

**Comment by 0xSherlokMo** [comment]
LGTM

**Comment by Filo13199** [comment]
LGTM

**Comment by cram0** [comment]
LGTM

**Comment by ShockAwer** [comment]
LGTM

**Review by yordadev — COMMENTED** [review]
✔️

**Comment by e9x** [comment]
This won't work and will fail to compile. We need to define the following features:

- `DDGStatsLibertarianFeature`
- `DDGStatsGreenPartyFeature`
- `DDGStatsIndependentFeature`

They belong in the following files:

https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/model/HomeFeatures.scala

**Comment by KingPedroDino** [comment]
Does this have a printed version I can review?

**Comment by TheLDB** [comment]
thanks to some great work by @e9x and @rubyji we now have properly defined features **and** support for socialist bias!

super excited to ship this, great work everyone 🚀

**Comment by nchristopher** [comment]
can confirm that this is blazingly fast ⚡

**Comment by ClaymorePT** [comment]
Communist party is missing.

**Comment by Marioood** [comment]
LGTM!

**Pull request closed without merging**
