### PR TITLE
Vastly improve timeline algorithm performance

### PR DESCRIPTION
**Pull request by super-cooper**
Bloat and bad code is removed, which should see multiple orders of magnitude in performance gains. Ineffective Tweet ranking code is also improved so that users will only see Tweets which increase their enjoyment of Twitter.

### CODE REVIEW

**Comment by Sethback** [comment]
Cringe af.

**Comment by kovashikawa** [comment]
working fine locally, it's ready to merge

**Comment by theCuratorCM** [comment]
WHERE IS CODE

**Comment by super-cooper** [comment]
> WHERE IS CODE

In an effort to slim down Twitter's bloated microservice container images, the code has been removed.

**Comment by gfodor** [comment]
delete the part

**Comment by super-cooper** [comment]
> delete the part

Out of scope for this change; please create a new JIRA ticket for next sprint

**Comment by toschdev** [comment]
That's a bit too much. Let's keep it productive <3

**Comment by eahrend** [comment]
Tested it out in our build environment, ship it to prod

**Comment by b72u68** [comment]
> WHERE IS CODE

Then you haven't heard about the best code practice: https://github.com/kelseyhightower/nocode

**Comment by NickJamesBTC** [comment]
Maybe make GH account requirements stricter, every twitter user is signing up now and while I enjoy a good shitpost it adds to the already massive volume of noise and makes it harder for good content to be noticed

**Comment by super-cooper** [comment]
I'm not actually a Twitter user. I spend most of my time on the US Fish & Wildlife administration website. Just here to support Elon Musk, who is doing very important work.

**Pull request closed without merging**
