### PR TITLE
feat(tweepcred): do not penalize until 1.0 friend-to-follower ratio

### PR DESCRIPTION
**Pull request by ctjlewis**
Updates `threshFriendsToFollowersRatioUMass` 0.6 -> 1.0. 

Currently, users are penalized >2500 following if their following-to-follower ratio exceeds 0.6. This is probably not appropriate, and it is more sensible to set this to 1.0.

### CODE REVIEW

**Comment by LericDax** [comment]
As others have pointed out with alacrity, this is deeply illogical and should be immediately amended to the rational ratio of 1:1.

**Comment by ctjlewis** [comment]
Note that this is an actual PR and not a joke one, would be good to get a review.

**Comment by Xetera** [comment]
I hope you're aware this was just elon's PR stunt (no pun intended) and Twitter has no intention of doing actual open source development on this repo

**Comment by ctjlewis** [comment]
Thanks for that note @Xetera, though strangely enough I don't remember anyone asking you a god damn thing.

**Comment by JoshuaSkootsky** [comment]
This make sense.

**Comment by ctjlewis** [comment]
@jdm-twtr - Trying to sign CLA but getting a rate limit error.

**Comment by yvesremmler** [comment]
As someone who follows many people out of curiosity, I agree.

**Pull request closed without merging**
