### PR TITLE
Puppy vs Bbq ribs? 

### PR DESCRIPTION
**Pull request by cdiaz19**
telegram-cloud-photo-size-1-5055643319253707374-y

telegram-cloud-photo-size-1-4969946850408903374-y

### CODE REVIEW

**Comment by RonnyCalderon** [comment]
This need to be approved right now!

**Review by otilor — COMMENTED** [review]
Doesn't LGTM

**Comment by pschroeder89** [comment]
Ship it!

**Comment by TheLDB** [comment]
my twitter usage would go up ~100-8,000% if approved & shipped. cc @elonmusk

**Comment by cyanblock** [comment]
Love the documentation attached! Merging Now!

**Pull request closed without merging**
