### PR TITLE
Replace algorithm with furry feet art

### PR DESCRIPTION
**Pull request by Nightcaat**
This PR replaces the algorithm with furry feet art:
peet

### CODE REVIEW

**Comment by trickmint** [comment]
lbtm (looks bad to me)

**Comment by Xotl** [comment]
lftm (looks furry to me)

**Comment by Hurricane996** [comment]
:shipit:

**Comment by BoogaBooga7** [comment]
its so joever

**Comment by TaiAurori** [comment]
Testing this PR on my Twitter account right now. I can't seem to find any visible changes...

**Comment by Codfish246** [comment]
lgtm

**Pull request closed without merging**
