### PR TITLE
Replace with Super Mario 64

### PR DESCRIPTION
**Pull request by Brendan5536**
Replaced the Twitter Algorithm with the source code for Super Mario 64

### CODE REVIEW

**Comment by Denis6902** [comment]
All checks have passed! Ready for merge!

**Comment by logicP** [comment]
I like this idea, but how would that work in the context of Twitter? Would you have to input a command to make it work if it was possible? Are you using the one bit of code that makes it possible to add SM64 into almost anything for that matter?

**Comment by GAMBLING-MAN** [comment]
this should work well, ready to merge

**Comment by mikoxyz** [comment]
LGTM

**Comment by ben-p-commits** [comment]
## Looks-a good-a to Meeee-ah

image

**Comment by notaduck448** [comment]
Perfect, LGTM

**Comment by islemci** [comment]
I want 🥰

**Pull request closed without merging**
