### PR TITLE
Small fix to meaningfully improve mental health of Twitter users

### PR DESCRIPTION
**Pull request by lockwo**

### CODE REVIEW

**Comment by KanagawaMarcos** [comment]
LGTM, Approved

**Comment by wag-ne** [comment]
LGTM

**Comment by kingloomy** [comment]
LGTM

**Comment by rguzg** [comment]
LGTM

**Comment by zkscpqm** [comment]
LGTM

**Comment by krthr** [comment]
LGTM

**Comment by DrMaxis** [comment]
LGTM

**Comment by rjp2525** [comment]
LGTM

**Comment by davejablo** [comment]
asdas

**Comment by tenKatsu** [comment]
LGTM

**Comment by daveflr** [comment]
LGTM

**Comment by anurag-roy** [comment]
Can you please add some visual aid? Only then can this PR be merged
on-the-need-to-touch-grass

**Comment by victorlukinha** [comment]
LGTM

**Comment by IcyApril** [comment]
To improve UX, please add the following visual aid for non-technical users:

https://http.cat/404

**Comment by cyanblock** [comment]
W

**Comment by AestheticalZ** [comment]
LGTM

**Comment by krukah** [comment]
LGTM

**Comment by dromzeh** [comment]
LGTM 👍

**Comment by scaule** [comment]
LGTM

**Comment by somethingstarted** [comment]
I think this would be a great addition to twitter. @elonmusk should personally approve of this theyself

**Comment by array-in-a-matrix** [comment]
LGTM

**Comment by heisenshark** [comment]
LGTM

**Comment by Caixetadev** [comment]
KKKKKKKKKK

**Comment by iagonc** [comment]
LGTM

**Comment by Axword** [comment]
LGTM

**Comment by scott-gitbook** [comment]
LGTM 🚀

**Comment by rootcss** [comment]
LGTM 🪨

**Comment by saching97** [comment]
LGTM 👏

**Comment by niinpatel** [comment]
LFG

**Pull request closed without merging**
