### PR TITLE
Update abusive_model.py

### PR DESCRIPTION
**Pull request by bbriggs1990**
Simplify the loop for iterating over physical_devices

### CODE REVIEW

**Comment by Smission** [comment]
lgtm

**Comment by Dev-Tarek** [comment]
it's cleaner to store the list in a new variable;
you can append something to it or change the source without having to changing the loop definition

**Comment by Smission** [comment]
@Dev-Tarek I think this is a preference more than anything and if done consistently, neither should be a problem. Also, even though insignificant, one might argue that declaring a variable only to use it once is wasting memory...

**Comment by Dev-Tarek** [comment]
> @Dev-Tarek I think this is a preference more than anything and if done consistently, neither should be a problem. Also, even though insignificant, one might argue that declaring a variable only to use it once is wasting memory...

for sure it is a preference, but it's not worth the time to create a the PR or call it simplification imo.
for sure i understand that most of the PRs in the ongoing marathon are just for fun :D

**Comment by bbriggs1990** [comment]
@Dev-Tarek @Smission It was just for fun lol. If only I knew removing this lone variable would be so controversial! XD

**Comment by puskuruk** [comment]
Just sad

**Comment by puskuruk** [comment]
It's just sad

**Pull request closed without merging**
