### PR TITLE
Elongated

### PR DESCRIPTION
**Pull request by Cillian1234**
Changed every instance of 'e' to "elon"

### CODE REVIEW

**Comment by NsdHSO** [comment]
I see that you added the `.idea` directory, why?
@twiter-team Please add `.idea` to `.gitignore`

**Comment by huseinnashr** [comment]
LGTM

**Comment by awwong1** [comment]
some high impact code right here, better print it out double sided

**Comment by rickvian** [comment]
you gotta follow the convention, it should be camelCase

please put Elon if there are any precedding text e.g thElon

**Comment by iswarmondal** [comment]
Respect👮! Take that AI

**Comment by moonrailgun** [comment]
I have no idea why xxxe will be `xxxelon`.

I has some problem, i think. because its will be loop themself. like `xxxelonlonlonlonlonlon......`

**Comment by ibreathebsb** [comment]
> I have no idea why xxxe will be `xxxelon`.
> 
> I has some problem, i think. because its will be loop themself. like `xxxelonlonlonlonlonlon......`
> 
> BTW, another problem is i cannot review this pr, i think microsoft programmer should test their page in benchmark image

works like "nnoremap" in vim

**Comment by xiaoyu2006** [comment]
LGTM. Nice work dude!

**Pull request closed without merging**
