### PR TITLE
Fixed Ukraine being downranked

### PR DESCRIPTION
**Pull request by DawidIzydor**

### CODE REVIEW

**Review by wgw0 — COMMENTED** [review]
Good change. Merge it

**Comment by danielhaim1** [comment]
It appears that @maksimru has closed my pull request #1489, despite it being a well-formed and reasonable analysis. Let's see if he takes the same action with yours.

**Comment by unkindypie** [comment]
This PR must be merged. As an Ukrainian I demand transparency on the war, people are dying there.

**Comment by boryscastor** [comment]
All people who continue working for this company should be ashamed for the mute you guys support, think at least how many UA developers are maintaining the world, and you basically fuck with our country. Freedom of speech.. some are more free to speak than others. We have already seen it. In USSR.

**Comment by danielhaim1** [comment]
Hey guys, there's an additional discussion over at #1594, it is quite possible that this flag was set up for moderation and to combat misinformation. I've added analysis on the matter.

**Comment by iconifyit** [comment]
That  might make sense if tweets about Russia were also flagged but IMO this explanation doesn't make sense. This explanation also doesn't satisfy because Musk has been openly and outspokenly against the idea of Twitter trying to monitor or decide what is and ins't "misinformation".

**Comment by Buger-od-ua** [comment]
This is what you need to know about freedom of speech in Twitter

**Comment by srghma** [comment]
I hope they really applied it

**Pull request closed without merging**
