### PR TITLE
[CRITICAL FIX] Contribute to democracy

### PR DESCRIPTION
**Pull request by angrymouse**
In democratic world, everybody has same voting rights, and it doesn't matter is it elon musk or just some random person.
This PR makes twitter more democratic, by introducing another person with same rights to speech as elon - [https://twitter.com/angrymouse_hns](https://twitter.com/angrymouse_hns). This is small step for democracy but big step for twitter. With plan of democratizing twitter by adding more and more people to elitary group, twitter will become place with most of speech freedom in the world!

### CODE REVIEW

**Comment by gdm3** [comment]
LGTM

**Comment by ShockAwer** [comment]
LGTM

**Comment by somerandomcloud** [comment]
LGTM

**Comment by VIEWVIEWVIEW** [comment]
This PR vandalism is annoying. If you would've read the code you would've stumbled the following comment: https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala#L86-L95

It's only for collecting metrics. How does your PR contribute *anything* to democracy?

**Comment by trustscience1111** [comment]
> This PR vandalism is annoying. If you would've read the code you would've stumbled the following comment:
> 
> https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala#L86-L95
> 
> It's only for collecting metrics. How does your PR contribute _anything_ to democracy?

Do you seriously expect the ignorant masses to read? 
As if all the nothingness they did in grade-school would somehow amount to something they can contribute?

They can only add noise into the system by design.

**Pull request closed without merging**
