### PR TITLE
🛑 Remove Political bias from Twitter

### PR DESCRIPTION
**Pull request by prashant-kikani**
Screenshot 2023-04-01 at 00-53-49 the-algorithm_HomeTweetTypePredicates scala at main · twitter_the-algorithm

### CODE REVIEW

**Comment by sunglocto** [comment]
LGTM

(the fact they had this at all is, embarassing)

**Comment by sharkey11** [comment]
HOLY SHIT

**Comment by HyflerSD** [comment]
What defines a dem or rep? Need to know how that algorithm decides this

**Comment by sajalkmr** [comment]
They probably will take this down soon lol.

**Comment by edoardottt** [comment]
history https://web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121

**Comment by somerandomcloud** [comment]
> (the fact they had this at all is, embarassing)
@sunglocto The fact that they had the balls to publish them openly influencing the political climate on twt is funny as fuck tho cant even lie

**Comment by znwhite** [comment]
`author_is_elon`

wtf even is this shit

**Comment by somerandomcloud** [comment]
self-centered bullfiller

**Comment by angrymouse** [comment]
LGTM!

**Comment by fbritoferreira** [comment]
This is just a way to add a tag to the tweet maybe so they can use for internal labels.

**Review by justizin — COMMENTED** [review]
Perfectly matches requirements, 10/10 no notes.

**Comment by MiguelMachado-dev** [comment]
Looks sexy, just ship it

**Comment by diguifi** [comment]
jesus christ I thought the screenshots were a joke

**Comment by guruevi** [comment]
> `author_is_elon`
> 
> wtf even is this shit

Making sure Elon doesn't get blocked. It's called a label, very useful in the training of your model (eg. this picture is a cat, this picture is a dog), that way it "knows" what a dog/cat is and can return those labels to humans.

**Comment by arkanttus** [comment]
LGTM

**Pull request closed without merging**
