### PR TITLE
home_mixer: fix has_gte_10k_favs boolean

### PR DESCRIPTION
**Pull request by matirko**
home_mixer: fix has_gte_10k_favs boolean

### CODE REVIEW

**Comment by greystorm101** [comment]
lgtm

**Comment by sfmqrb** [comment]
lgtm

**Review by Codfish246 — COMMENTED** [review]
lgtm

**Comment by ludo6577** [comment]
Did you read all the code to find this one? Nice catch! :)

**Comment by samsullivan** [comment]
Impressive.

**Comment by samsullivan** [comment]
Impressive.

**Comment by dav1312** [comment]
Duplicate of https://github.com/twitter/the-algorithm/pull/572

**Pull request closed without merging**
