### PR TITLE
Fix Ukraine censorship

### PR DESCRIPTION
**Pull request by gizahNL**

### CODE REVIEW

**Review by wgw0 — COMMENTED** [review]
Good change. Merge it.

**Review by DiarmaidMckeagney — COMMENTED** [review]
Removal of down ranking for Ukraine post all fine, however removal of policy violation could have unforeseen consequences on misinformation. Devs probably will not merge this code.

**Comment by wgw0** [comment]
> Removal of down ranking for Ukraine post all fine, however removal of policy violation could have unforeseen consequences on misinformation. Devs probably will not merge this code.

I doubt they will be merging any code at all any time soon. 😆

**Comment by maksimru** [comment]
duplicates https://github.com/twitter/the-algorithm/pull/1524

**Pull request closed without merging**
